import { supabase } from "@/lib/supabaseClient"; import type { ReceivablesListResult } from "./types";
async function token() { const { data } = await supabase.auth.getSession(); if (!data.session?.access_token) throw new Error("Sign in again to continue."); return data.session.access_token; }
export async function fetchReceivables(query = ""): Promise<ReceivablesListResult> { const response = await fetch(`/api/receivables${query}`, { headers: { Authorization: `Bearer ${await token()}` }, cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Payment Collections are unavailable."); return result; }
type PendingCommand={command:Record<string,unknown>;createdAt:string};
async function session(){const {data}=await supabase.auth.getSession();if(!data.session?.access_token||!data.session.user.id)throw new Error("Sign in again to continue.");return {token:data.session.access_token,userId:data.session.user.id}}
function outboxKey(userId:string){return `zerodata:receivables-outbox:${userId}`}
function readOutbox(userId:string):PendingCommand[]{try{return JSON.parse(localStorage.getItem(outboxKey(userId))??"[]") as PendingCommand[]}catch{return []}}
function writeOutbox(userId:string,items:PendingCommand[]){localStorage.setItem(outboxKey(userId),JSON.stringify(items))}
async function send(command:Record<string,unknown>,accessToken:string){const response=await fetch("/api/receivables/commands",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify(command)});const result=await response.json();if(!response.ok){const error=new Error(result.message??"The command was not confirmed.") as Error&{code?:string;current?:unknown};error.code=result.code;error.current=result.current;throw error}return result}
export async function executeReceivableCommand(command:Record<string,unknown>){if(!navigator.onLine)throw new Error("An internet connection is required for financial actions.");const auth=await session(),operationId=String(command.operation_id??"");const existing=readOutbox(auth.userId),pending=existing.some(item=>String(item.command.operation_id)===operationId)?existing:[...existing,{command,createdAt:new Date().toISOString()}];writeOutbox(auth.userId,pending);const result=await send(command,auth.token);writeOutbox(auth.userId,readOutbox(auth.userId).filter(item=>String(item.command.operation_id)!==operationId));return result}
export async function recoverReceivableCommands(){if(!navigator.onLine)return {confirmed:0,pending:0};const auth=await session();let confirmed=0;for(const item of readOutbox(auth.userId)){try{await send(item.command,auth.token);writeOutbox(auth.userId,readOutbox(auth.userId).filter(candidate=>candidate.command.operation_id!==item.command.operation_id));confirmed++}catch{/* Exact command remains owner-scoped for explicit retry/reconciliation. */}}return {confirmed,pending:readOutbox(auth.userId).length}}
