import "server-only";
import { createHash } from "crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ImportRow } from "./import";
import { requestHash } from "./server";
import { getCurrentISTDate } from "@/lib/dateTime";
import { importPreviewBinding } from "./importBinding";
import { listEligibleOperationalEmployees } from "@/lib/employees/server";

export type ImportClassification="NEW"|"EXACT_DUPLICATE"|"CONFLICTING_DUPLICATE"|"INVALID_EMPLOYEE"|"INVALID"|"INVALID_DISTRIBUTOR"|"INVALID_DISTRIBUTOR_STATUS"|"AMBIGUOUS_DISTRIBUTOR";
export interface ClassifiedImportRow extends ImportRow {classification:ImportClassification;reason?:string;assigned_to?:string;assigned_employee_name?:string;receivable_id?:string;business_key?:string;distributor_id?:string;resolved_distributor_name?:string}
export interface ImportPreview {rows:ClassifiedImportRow[];counts:{new:number;exactDuplicate:number;conflict:number;invalid:number};preview_hash:string;resolvedRows:Record<string,unknown>[]}

function normalized(value:string){return value.trim().replace(/\s+/g," ").toLowerCase()}
export function importBusinessIdentity(row:Pick<ImportRow,"distributorCode"|"distributorName"|"billReference">){const distributor=row.distributorCode.trim()?`code:${normalized(row.distributorCode)}`:`name:${normalized(row.distributorName)}`;return {distributor,bill:normalized(row.billReference),key:`${distributor}|${normalized(row.billReference)}`}}
function critical(row:ImportRow,assignedTo:string){return requestHash({billAmount:row.billAmount,billDueDate:row.billDueDate,nextFollowUpDate:row.nextFollowUpDate,assignedTo,contactPerson:row.contactPerson.trim(),contactPhone:row.contactPhone.trim()})}
function existingCritical(row:Record<string,unknown>){return requestHash({billAmount:String(row.bill_amount),billDueDate:String(row.bill_due_date),nextFollowUpDate:String(row.next_follow_up_date??""),assignedTo:String(row.assigned_to),contactPerson:String(row.contact_person).trim(),contactPhone:String(row.contact_phone??"").trim()})}
function stableRowId(operationId:string,rowNumber:number){const hex=createHash("sha256").update(`${operationId}:${rowNumber}`).digest("hex");return `${hex.slice(0,8)}-${hex.slice(8,12)}-4${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`}
async function chunks<T>(items:T[],size:number,fn:(chunk:T[])=>Promise<Record<string,unknown>[]>){const rows:Record<string,unknown>[]=[];for(let index=0;index<items.length;index+=size)rows.push(...await fn(items.slice(index,index+size)));return rows}
function distributorResolutionReason(resolution:ImportClassification,usedCode:boolean){if(resolution==="AMBIGUOUS_DISTRIBUTOR")return "More than one Distributor Status record has this exact name.";if(resolution==="INVALID_DISTRIBUTOR_STATUS")return "The exact Distributor Status record is not billed.";return usedCode?"Distributor Code does not exactly match a Distributor Status reference.":"Distributor Name does not exactly match a Distributor Status record."}

export async function buildImportPreview(service:SupabaseClient,operationId:string,rows:ImportRow[]):Promise<ImportPreview>{
 const directory=await listEligibleOperationalEmployees(service);if(directory.error)throw directory.error;const activeByEmail=new Map(directory.employees.map(user=>[user.email.trim().toLowerCase(),user.user_id])),nameById=new Map(directory.employees.map(user=>[user.user_id,user.name]));
 const {data:resolutionRows,error:resolutionError}=await service.rpc("resolve_receivable_distributors_v1",{p_rows:rows.map(row=>({row_number:row.rowNumber,distributor_code:row.distributorCode,distributor_name:row.distributorName}))});if(resolutionError)throw resolutionError;type DistributorResolution={row_number:number;distributor_id:string|null;distributor_name:string|null;distributor_reference:string|null;resolution:string};const resolutions=new Map<number,DistributorResolution>(((resolutionRows??[]) as unknown[]).map((row:unknown)=>{const value=row as DistributorResolution;return [value.row_number,value]}));
 const identities=rows.map(importBusinessIdentity),distributorIds=[...new Set([...resolutions.values()].map(row=>row.distributor_id).filter((value):value is string=>Boolean(value)))];const existing=await chunks(distributorIds,100,async chunk=>{const {data,error}=await service.from("receivables").select("receivable_id,distributor_id,bill_reference_key,bill_amount,bill_due_date,next_follow_up_date,assigned_to,contact_person,contact_phone").in("distributor_id",chunk);if(error)throw error;return data??[]});const existingByKey=new Map(existing.map(row=>[`${row.distributor_id}|${row.bill_reference_key}`,row]));
 const seen=new Map<string,string>();const classified:ClassifiedImportRow[]=[];const resolvedRows:Record<string,unknown>[]=[],today=getCurrentISTDate();
 rows.forEach((row,index)=>{const assignedTo=activeByEmail.get(row.assignedEmployeeEmail.toLowerCase());const identity=identities[index],resolved=resolutions.get(row.rowNumber);if(!resolved||resolved.resolution!=="RESOLVED"||!resolved.distributor_id){const classification=(resolved?.resolution??"INVALID_DISTRIBUTOR") as ImportClassification;classified.push({...row,classification,reason:distributorResolutionReason(classification,Boolean(row.distributorCode.trim())),business_key:identity.key});return}const canonicalKey=`distributor:${resolved.distributor_id}|${identity.bill}`;if(row.nextFollowUpDate<today){classified.push({...row,classification:"INVALID",reason:"Payment Follow-up Date must be today or later.",business_key:canonicalKey,distributor_id:resolved.distributor_id});return}if(!assignedTo){classified.push({...row,classification:"INVALID_EMPLOYEE",reason:"Assigned employee is missing, inactive, or not an operational employee.",business_key:canonicalKey,distributor_id:resolved.distributor_id});return}const signature=critical(row,assignedTo),prior=seen.get(canonicalKey),current=existingByKey.get(`${resolved.distributor_id}|${identity.bill}`);let classification:ImportClassification="NEW",reason:string|undefined;if(prior){classification=prior===signature?"EXACT_DUPLICATE":"CONFLICTING_DUPLICATE";reason=classification==="EXACT_DUPLICATE"?"Repeated exact business identity in this file.":"The same business identity has conflicting values in this file."}else if(current){classification=existingCritical(current)===signature?"EXACT_DUPLICATE":"CONFLICTING_DUPLICATE";reason=classification==="EXACT_DUPLICATE"?"An authoritative matching receivable already exists.":"An authoritative receivable with this identity has different critical values."}seen.set(canonicalKey,signature);const receivableId=stableRowId(operationId,row.rowNumber);classified.push({...row,classification,reason,assigned_to:assignedTo,assigned_employee_name:nameById.get(assignedTo),receivable_id:receivableId,business_key:canonicalKey,distributor_id:resolved.distributor_id,resolved_distributor_name:resolved.distributor_name??undefined});resolvedRows.push({row_number:row.rowNumber,receivable_id:receivableId,distributor_id:resolved.distributor_id,bill_reference:row.billReference,distributor_name:resolved.distributor_name,distributor_code:resolved.distributor_reference,contact_person:row.contactPerson,contact_phone:row.contactPhone,bill_amount:row.billAmount,bill_due_date:row.billDueDate,next_follow_up_date:row.nextFollowUpDate,assigned_to:assignedTo,notes:row.notes})});
 const counts={new:classified.filter(row=>row.classification==="NEW").length,exactDuplicate:classified.filter(row=>row.classification==="EXACT_DUPLICATE").length,conflict:classified.filter(row=>row.classification==="CONFLICTING_DUPLICATE").length,invalid:classified.filter(row=>["INVALID_EMPLOYEE","INVALID","INVALID_DISTRIBUTOR","INVALID_DISTRIBUTOR_STATUS","AMBIGUOUS_DISTRIBUTOR"].includes(row.classification)).length};const preview_hash=requestHash(importPreviewBinding(classified,resolvedRows));
 return {rows:classified,counts,preview_hash,resolvedRows};
}
