import "server-only";
import { createHash } from "crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ImportRow } from "./import";
import { requestHash } from "./server";

export type ImportClassification="NEW"|"EXACT_DUPLICATE"|"CONFLICTING_DUPLICATE"|"INVALID_EMPLOYEE"|"INVALID";
export interface ClassifiedImportRow extends ImportRow {classification:ImportClassification;reason?:string;assigned_to?:string;receivable_id?:string;business_key?:string}
export interface ImportPreview {rows:ClassifiedImportRow[];counts:{new:number;exactDuplicate:number;conflict:number;invalid:number};preview_hash:string;resolvedRows:Record<string,unknown>[]}

function normalized(value:string){return value.trim().replace(/\s+/g," ").toLowerCase()}
export function importBusinessIdentity(row:Pick<ImportRow,"distributorCode"|"distributorName"|"billReference">){const distributor=row.distributorCode.trim()?`code:${normalized(row.distributorCode)}`:`name:${normalized(row.distributorName)}`;return {distributor,bill:normalized(row.billReference),key:`${distributor}|${normalized(row.billReference)}`}}
function critical(row:ImportRow,assignedTo:string){return requestHash({billAmount:row.billAmount,billDueDate:row.billDueDate,nextFollowUpDate:row.nextFollowUpDate,assignedTo,contactPerson:row.contactPerson.trim(),contactPhone:row.contactPhone.trim()})}
function existingCritical(row:Record<string,unknown>){return requestHash({billAmount:String(row.bill_amount),billDueDate:String(row.bill_due_date),nextFollowUpDate:String(row.next_follow_up_date??""),assignedTo:String(row.assigned_to),contactPerson:String(row.contact_person).trim(),contactPhone:String(row.contact_phone??"").trim()})}
function stableRowId(operationId:string,rowNumber:number){const hex=createHash("sha256").update(`${operationId}:${rowNumber}`).digest("hex");return `${hex.slice(0,8)}-${hex.slice(8,12)}-4${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`}
async function chunks<T>(items:T[],size:number,fn:(chunk:T[])=>Promise<Record<string,unknown>[]>){const rows:Record<string,unknown>[]=[];for(let index=0;index<items.length;index+=size)rows.push(...await fn(items.slice(index,index+size)));return rows}

export async function buildImportPreview(service:SupabaseClient,operationId:string,rows:ImportRow[]):Promise<ImportPreview>{
 const emails=[...new Set(rows.map(row=>row.assignedEmployeeEmail.toLowerCase()))];const users=await chunks(emails,100,async chunk=>{const {data,error}=await service.from("users").select("user_id,email,is_active").in("email",chunk);if(error)throw error;return data??[]});const activeByEmail=new Map(users.filter(user=>user.is_active===true||user.is_active===1).map(user=>[String(user.email).toLowerCase(),String(user.user_id)]));
 const identities=rows.map(importBusinessIdentity),distributors=[...new Set(identities.map(identity=>identity.distributor))];const existing=await chunks(distributors,100,async chunk=>{const {data,error}=await service.from("receivables").select("receivable_id,distributor_identity_key,bill_reference_key,bill_amount,bill_due_date,next_follow_up_date,assigned_to,contact_person,contact_phone").in("distributor_identity_key",chunk);if(error)throw error;return data??[]});const existingByKey=new Map(existing.map(row=>[`${row.distributor_identity_key}|${row.bill_reference_key}`,row]));
 const seen=new Map<string,string>();const classified:ClassifiedImportRow[]=[];const resolvedRows:Record<string,unknown>[]=[];
 rows.forEach((row,index)=>{const assignedTo=activeByEmail.get(row.assignedEmployeeEmail.toLowerCase());const identity=identities[index];if(!assignedTo){classified.push({...row,classification:"INVALID_EMPLOYEE",reason:"Assigned employee is missing or inactive.",business_key:identity.key});return}const signature=critical(row,assignedTo),prior=seen.get(identity.key),current=existingByKey.get(identity.key);let classification:ImportClassification="NEW",reason:string|undefined;if(prior){classification=prior===signature?"EXACT_DUPLICATE":"CONFLICTING_DUPLICATE";reason=classification==="EXACT_DUPLICATE"?"Repeated exact business identity in this file.":"The same business identity has conflicting values in this file."}else if(current){classification=existingCritical(current)===signature?"EXACT_DUPLICATE":"CONFLICTING_DUPLICATE";reason=classification==="EXACT_DUPLICATE"?"An authoritative matching receivable already exists.":"An authoritative receivable with this identity has different critical values."}seen.set(identity.key,signature);const receivableId=stableRowId(operationId,row.rowNumber);classified.push({...row,classification,reason,assigned_to:assignedTo,receivable_id:receivableId,business_key:identity.key});resolvedRows.push({row_number:row.rowNumber,receivable_id:receivableId,bill_reference:row.billReference,distributor_name:row.distributorName,distributor_code:row.distributorCode,contact_person:row.contactPerson,contact_phone:row.contactPhone,bill_amount:row.billAmount,bill_due_date:row.billDueDate,next_follow_up_date:row.nextFollowUpDate,assigned_to:assignedTo,notes:row.notes})});
 const counts={new:classified.filter(row=>row.classification==="NEW").length,exactDuplicate:classified.filter(row=>row.classification==="EXACT_DUPLICATE").length,conflict:classified.filter(row=>row.classification==="CONFLICTING_DUPLICATE").length,invalid:classified.filter(row=>row.classification==="INVALID_EMPLOYEE"||row.classification==="INVALID").length};const preview_hash=requestHash(classified.map(({classification,business_key,assigned_to,rowNumber,billAmount,billDueDate,nextFollowUpDate})=>({classification,business_key,assigned_to,rowNumber,billAmount,billDueDate,nextFollowUpDate})));
 return {rows:classified,counts,preview_hash,resolvedRows};
}
