import { apiError, contextFor, isReceivablesReady } from "@/lib/receivables/server";
import { distributorReady } from "@/lib/distributors/server";
export const dynamic="force-dynamic";
export async function GET(request:Request){
 if(!isReceivablesReady())return apiError(503,"RECEIVABLES_UNAVAILABLE","Payment Collections are not activated yet."); const context=await contextFor(request); if(!context)return apiError(401,"AUTH_REQUIRED","Sign in again."); if(!context.isAdmin)return apiError(403,"ADMIN_REQUIRED","System Administrator access required.");
 const detailId=new URL(request.url).searchParams.get("receivable_id");
 if(detailId){const [{data:receivable,error:receivableError},{data:payments,error:paymentsError,count:paymentCount},{data:activity,error:activityError,count:activityCount},{data:identity}]=await Promise.all([context.service.from("receivables_financial_read_v1").select("receivable_id,bill_reference,distributor_name,contact_person,contact_phone,bill_amount,confirmed_paid_amount,outstanding_amount,bill_due_date,next_follow_up_date,assigned_to,lifecycle_status,payment_state,alert_state,version,pending_payment_count,aging_bucket,promise_date").eq("receivable_id",detailId).maybeSingle(),context.service.from("receivable_payments").select("payment_id,receivable_id,amount,payment_date,payment_mode,payment_reference,note,verification_status,reported_by,reported_at,verified_by,verified_at,reversed_at",{count:"exact"}).eq("receivable_id",detailId).order("reported_at",{ascending:false}).range(0,49),context.service.from("receivable_activity_events").select("activity_id,receivable_id,event_type,note,change_set,actor_id,created_at",{count:"exact"}).eq("receivable_id",detailId).order("created_at",{ascending:false}).range(0,49),context.service.from("receivables").select("distributor_identity_key").eq("receivable_id",detailId).maybeSingle()]);if(receivableError||paymentsError||activityError||!receivable)return apiError(404,"RECEIVABLE_NOT_FOUND","Receivable detail is unavailable.");let distributorStatus=null;if(identity?.distributor_identity_key&&distributorReady()){const {data:matches}=await context.service.from("distributor_accounts").select("distributor_id,renewal_date").eq("identity_key",identity.distributor_identity_key).limit(2);if(matches?.length===1)distributorStatus={...matches[0],renewal_state:null}}return Response.json({receivable:{...receivable,owner_name:"Assigned employee"},payments,activity,distributor_status:distributorStatus,history:{limit:50,payment_count:paymentCount??0,payment_has_more:(paymentCount??0)>50,activity_count:activityCount??0,activity_has_more:(activityCount??0)>50}});}
 const [{data:metrics,error:metricError},{data:payments,error:paymentError,count:pendingCount},{data:users,error:userError},{data:adminCapabilities,error:capabilityError}]=await Promise.all([context.service.rpc("receivables_admin_metrics_v1",{p_actor_id:context.userId}),context.service.from("receivable_payments").select("payment_id,receivable_id,amount,payment_date,payment_mode,payment_reference,note,reported_by,reported_at",{count:"exact"}).eq("verification_status","reported").order("reported_at",{ascending:true}).range(0,49),context.service.from("users").select("user_id,name,email,is_active").eq("is_active",true).order("name"),context.service.from("user_capabilities").select("user_id").eq("capability_code","admin")]);if(metricError||paymentError||userError||capabilityError)return apiError(503,"READ_FAILED","Admin collection summary could not be loaded.");
 const receivableIds=[...new Set((payments??[]).map(p=>p.receivable_id))],reporterIds=[...new Set((payments??[]).map(p=>p.reported_by))];const [{data:receivables},{data:reporters}]=await Promise.all([receivableIds.length?context.service.from("receivables_financial_read_v1").select("receivable_id,distributor_name,bill_reference,outstanding_amount,version").in("receivable_id",receivableIds):{data:[]},reporterIds.length?context.service.from("users").select("user_id,name").in("user_id",reporterIds):{data:[]}]);const bills=new Map((receivables??[]).map(r=>[r.receivable_id,r])),names=new Map((reporters??[]).map(r=>[r.user_id,r.name])),adminIds=new Set((adminCapabilities??[]).map(capability=>capability.user_id)),assignees=(users??[]).filter(user=>!adminIds.has(user.user_id)).map(({user_id,name,email})=>({user_id,name,email}));return Response.json({metrics,assignees,pending:(payments??[]).map(p=>({...p,receivable:bills.get(p.receivable_id),reporter_name:names.get(p.reported_by)??"Employee"})),pending_count:pendingCount??0,pending_has_more:(pendingCount??0)>50});
}
