import { apiError, contextFor, isReceivablesReady } from "@/lib/receivables/server";
export const dynamic="force-dynamic";
export async function GET(request:Request){
 if(!isReceivablesReady())return apiError(503,"RECEIVABLES_UNAVAILABLE","Payment Collections are not activated yet."); const context=await contextFor(request); if(!context)return apiError(401,"AUTH_REQUIRED","Sign in again."); if(!context.isAdmin)return apiError(403,"ADMIN_REQUIRED","System Administrator access required.");
 const detailId=new URL(request.url).searchParams.get("receivable_id");
 if(detailId){const [{data:receivable,error:receivableError},{data:payments,error:paymentsError},{data:activity,error:activityError}]=await Promise.all([context.service.from("receivables_financial_read_v1").select("*").eq("receivable_id",detailId).maybeSingle(),context.service.from("receivable_payments").select("*").eq("receivable_id",detailId).order("reported_at",{ascending:false}).limit(200),context.service.from("receivable_activity_events").select("*").eq("receivable_id",detailId).order("created_at",{ascending:false}).limit(200)]);if(receivableError||paymentsError||activityError||!receivable)return apiError(404,"RECEIVABLE_NOT_FOUND","Receivable detail is unavailable.");return Response.json({receivable,payments,activity});}
 const [{data:metrics,error:metricError},{data:payments,error:paymentError}]=await Promise.all([context.service.rpc("receivables_admin_metrics_v1",{p_actor_id:context.userId}),context.service.from("receivable_payments").select("payment_id,receivable_id,amount,payment_date,payment_mode,payment_reference,note,reported_by,reported_at").eq("verification_status","reported").order("reported_at",{ascending:true}).limit(50)]);if(metricError||paymentError)return apiError(503,"READ_FAILED","Admin collection summary could not be loaded.");
 const receivableIds=[...new Set((payments??[]).map(p=>p.receivable_id))],reporterIds=[...new Set((payments??[]).map(p=>p.reported_by))];const [{data:receivables},{data:reporters}]=await Promise.all([receivableIds.length?context.service.from("receivables_financial_read_v1").select("receivable_id,distributor_name,bill_reference,outstanding_amount,version").in("receivable_id",receivableIds):{data:[]},reporterIds.length?context.service.from("users").select("user_id,name").in("user_id",reporterIds):{data:[]}]);const bills=new Map((receivables??[]).map(r=>[r.receivable_id,r])),names=new Map((reporters??[]).map(r=>[r.user_id,r.name]));return Response.json({metrics,pending:(payments??[]).map(p=>({...p,receivable:bills.get(p.receivable_id),reporter_name:names.get(p.reported_by)??"Employee"}))});
}
