import { distributorListSchema } from "@/lib/distributors/validation";
import { apiError,contextFor,distributorReadError } from "@/lib/distributors/server";
import { renewalState } from "@/lib/distributors/domain";
import { addISTDateDays,getCurrentISTDate } from "@/lib/dateTime";
export const dynamic="force-dynamic";
const columns="distributor_id,distributor_name,distributor_reference,lead_id,phone,city,assigned_to,installation_status,installation_completed_at,training_status,training_completed_at,mapping_status,mapped_at,activity_status,billing_status,billed_at,bill_reference,renewal_date,version,updated_at";
export async function GET(request:Request){
 const context=await contextFor(request);if(!context)return apiError(401,"AUTH_REQUIRED","Sign in again.");
 const url=new URL(request.url),parsed=distributorListSchema.safeParse(Object.fromEntries(url.searchParams));if(!parsed.success)return apiError(400,"INVALID_FILTERS",parsed.error.issues[0]?.message??"Invalid filters.");const f=parsed.data,from=(f.page-1)*f.pageSize;
 const {data,error}=await context.service.rpc("distributor_financial_projection_v1",{p_actor_id:context.userId,p_page:f.page,p_page_size:f.pageSize,p_search:f.search||null,p_assigned_to:context.isAdmin?(f.assignedTo||null):null,p_payment_filter:f.paymentStatus||null,p_billing_filter:f.billing||null});if(error){if(f.paymentStatus)return apiError(503,"CANONICAL_COLLECTIONS_UNAVAILABLE","Canonical collection filters become available after Migration 045.");let query=context.service.from("distributor_accounts").select(columns,{count:"exact"});if(!context.isAdmin)query=query.eq("assigned_to",context.userId);if(f.search){const safe=f.search.replace(/[,%()]/g," ").trim();if(safe)query=query.or(`distributor_name.ilike.%${safe}%,distributor_reference.ilike.%${safe}%`)}if(f.assignedTo&&context.isAdmin)query=query.eq("assigned_to",f.assignedTo);if(f.installation)query=query.eq("installation_status",f.installation);if(f.training)query=query.eq("training_status",f.training);if(f.mapping)query=query.eq("mapping_status",f.mapping);if(f.activity)query=query.eq("activity_status",f.activity);if(f.billing)query=query.eq("billing_status",f.billing);const today=getCurrentISTDate();if(f.renewal==="due_soon")query=query.lte("renewal_date",addISTDateDays(today,2));const legacy=await query.order("updated_at",{ascending:false}).order("distributor_id",{ascending:false}).range(from,from+f.pageSize-1);if(legacy.error)return distributorReadError(legacy.error);const ownerIds=[...new Set((legacy.data??[]).map(row=>row.assigned_to))],owners=ownerIds.length?await context.service.from("users").select("user_id,name").in("user_id",ownerIds):{data:[],error:null};if(owners.error)return apiError(503,"EMPLOYEE_DIRECTORY_UNAVAILABLE","Assigned employee names could not be loaded.");const names=new Map((owners.data??[]).map(owner=>[owner.user_id,owner.name]));return Response.json({rows:(legacy.data??[]).map(row=>({...row,assigned_employee_name:names.get(row.assigned_to)??"Assigned employee",renewal_state:renewalState(row.renewal_date,today)})),page:f.page,pageSize:f.pageSize,total:legacy.count??0,canonical_collections_ready:false});}const result=data as {rows:Record<string,unknown>[];total:number},today=getCurrentISTDate();const ownerIds=[...new Set((result.rows??[]).map(row=>String(row.assigned_to)))],ownersResult=ownerIds.length?await context.service.from("users").select("user_id,name").in("user_id",ownerIds):{data:[],error:null};if(ownersResult.error)return apiError(503,"EMPLOYEE_DIRECTORY_UNAVAILABLE","Assigned employee names could not be loaded.");const names=new Map((ownersResult.data??[]).map(owner=>[owner.user_id,owner.name]));return Response.json({rows:(result.rows??[]).map(row=>({...row,assigned_employee_name:names.get(String(row.assigned_to))??"Assigned employee",renewal_state:renewalState(String(row.renewal_date??""),today)})),page:f.page,pageSize:f.pageSize,total:result.total??0,canonical_collections_ready:true});
}
