import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { git, gitEnvironmentFor, repositoryIdentity, root } from "./kernel-lib.mjs";
import { makeEngineeringTemp, removeEngineeringTemp } from "./managed-paths.mjs";
import { inspectWorkspaceSuitability } from "./task-controller.mjs";
import { createTask, listTasks, loadTask, taskDirectory, updateTaskState } from "./task-state.mjs";
import { assertTaskCompatibility, loadState, resolveOrBindSessionTask, sessionPath } from "./hooks/state-store.mjs";

const taskRoot = makeEngineeringTemp("continuity-task-state"), sessionRoot = makeEngineeringTemp("continuity-session-state"), previousTaskRoot = process.env.ZD_OS_STATE_ROOT, previousSessionRoot = process.env.ZD_OS_SESSION_ROOT, previousPrFixture = process.env.ZD_OS_RECOVERY_PR_FIXTURE, suffix = randomUUID().slice(0, 8), fixtureBranch = `chore/kernel-recovery-fixture-${suffix}`;
const repository = dirname(git("rev-parse", "--path-format=absolute", "--git-common-dir")), fixture = resolve(repository, ".worktrees", `kernel recovery fixture ${suffix}`), gitAt = (cwd, ...args) => execFileSync("git", ["-c", "core.hooksPath=", ...args], { cwd, encoding: "utf8", env: { ...gitEnvironmentFor(cwd), GIT_AUTHOR_NAME: "CRM Hook Fixture", GIT_AUTHOR_EMAIL: "fixture@example.invalid", GIT_COMMITTER_NAME: "CRM Hook Fixture", GIT_COMMITTER_EMAIL: "fixture@example.invalid" }, maxBuffer: 64 << 20 }).trim();
process.env.ZD_OS_STATE_ROOT = taskRoot; process.env.ZD_OS_SESSION_ROOT = sessionRoot;

const runHook = (name, input, env = process.env) => {
  const result = spawnSync(process.execPath, [`scripts/engineering/hooks/${name}.mjs`], { cwd: fixture, encoding: "utf8", env, input: JSON.stringify(input) });
  assert.equal(result.status, 0, `${name}: ${result.stderr || result.stdout}`); const output = result.stdout.trim(); return output ? JSON.parse(output) : null;
};
const automatic = (result) => JSON.parse(result.hookSpecificOutput.additionalContext);
const taskFiles = (taskId) => ["task.json", "acceptance.json", "plan.json", "proof.json", "delivery.json"].map((name) => readFileSync(resolve(taskDirectory(taskId), name), "utf8"));
const complete = (taskId) => { const task = loadTask(taskId); updateTaskState(taskId, task.revision, { taskPatch: { status: "COMPLETE" }, progress: [{ event: "TASK_COMPLETED" }] }); };
const newTaskContext = { schemaVersion: 1, status: "RESOLVED", risk: "R3", domains: ["engineering-control"], authorities: [], capabilities: [], candidatePaths: [], requiredProofRefs: [] };

try {
  gitAt(root, "worktree", "add", "-b", fixtureBranch, fixture, "HEAD");
  cpSync(resolve(root, "scripts/engineering"), resolve(fixture, "scripts/engineering"), { recursive: true, force: true }); cpSync(resolve(root, "docs/engineering"), resolve(fixture, "docs/engineering"), { recursive: true, force: true }); cpSync(resolve(root, "docs/contracts/engineering-os.md"), resolve(fixture, "docs/contracts/engineering-os.md"), { force: true }); cpSync(resolve(root, ".codex/hooks.json"), resolve(fixture, ".codex/hooks.json"), { force: true }); cpSync(resolve(root, "package.json"), resolve(fixture, "package.json"), { force: true }); cpSync(resolve(root, "AGENTS.md"), resolve(fixture, "AGENTS.md"), { force: true });
  gitAt(fixture, "add", "scripts/engineering", "docs/engineering", "docs/contracts/engineering-os.md", ".codex/hooks.json", "package.json", "AGENTS.md"); if (spawnSync("git", ["diff", "--cached", "--quiet"], { cwd: fixture, env: gitEnvironmentFor(fixture) }).status === 1) gitAt(fixture, "commit", "-m", "test: current kernel recovery fixture");
  const initialHead = gitAt(fixture, "rev-parse", "HEAD"), identity = { branch: fixtureBranch, worktree: fixture, repositoryCommonGitDir: gitAt(fixture, "rev-parse", "--path-format=absolute", "--git-common-dir"), ...repositoryIdentity(fixture) };
  process.env.ZD_OS_RECOVERY_PR_FIXTURE = JSON.stringify([{ number: 999, headRefName: fixtureBranch, headRefOid: initialHead, baseRefName: "main", baseRefOid: gitAt(fixture, "rev-parse", "origin/main"), isDraft: false }]);

  const primaryBranch = gitAt(repository, "branch", "--show-current"), primaryRepository = repositoryIdentity(repository), primaryIdentity = { branch: primaryBranch, worktree: repository, repositoryCommonGitDir: gitAt(repository, "rev-parse", "--path-format=absolute", "--git-common-dir"), repository: primaryRepository }; assert.equal(resolveOrBindSessionTask(`bootstrap-${suffix}`, { identity: primaryIdentity }).resolution, "AWAITING_TASK");

  const configured = JSON.parse(readFileSync(resolve(fixture, ".codex/hooks.json"), "utf8")).hooks, inputs = { SessionStart: { session_id: `entry-start-${suffix}`, source: "startup" }, UserPromptSubmit: { session_id: `entry-prompt-${suffix}`, prompt: "status" }, PreToolUse: { session_id: `entry-pre-${suffix}`, tool_name: "exec_command", tool_input: { cmd: "git status --short" } }, PostToolUse: { session_id: `entry-post-${suffix}`, tool_name: "exec_command", tool_input: { cmd: "git status --short" }, tool_response: { exit_code: 0, stdout: "", stderr: "" } }, Stop: { session_id: `entry-stop-${suffix}` } }; assert.deepEqual(configured, {});
  const scriptsByEvent = { SessionStart: "session-start", UserPromptSubmit: "user-prompt", PreToolUse: "pre-tool", PostToolUse: "post-tool", Stop: "stop" };
  for (const [event, input] of Object.entries(inputs)) {
    const script = scriptsByEvent[event], command = `git -c alias.zd-hook=!node zd-hook scripts/engineering/hooks/${script}.mjs`, result = process.platform === "win32" ? spawnSync(process.env.ComSpec ?? "cmd.exe", ["/D", "/S", "/C", command], { cwd: fixture, encoding: "utf8", env: process.env, input: JSON.stringify(input) }) : spawnSync(process.execPath, [`scripts/engineering/hooks/${script}.mjs`], { cwd: fixture, encoding: "utf8", env: process.env, input: JSON.stringify(input) });
    assert.equal(result.status, 0, `${event}: ${result.stderr || result.stdout}`); assert.equal(result.stderr, "", event);
  }

  const orphanSession = `orphan-${suffix}`, promptFirst = automatic(runHook("user-prompt", { session_id: orphanSession, prompt: "status" })); assert.equal(promptFirst.sessionStatus, "RECOVERY_REQUIRED"); assert.equal(promptFirst.recovery.action, "RESUME_CURRENT_WORKSPACE"); assert.equal(loadState(orphanSession).boundTaskId, undefined);
  const fresh = automatic(runHook("session-start", { session_id: orphanSession, source: "startup" })); assert.equal(fresh.sessionStatus, "RECOVERY_REQUIRED"); assert.equal(fresh.recovery.action, "RESUME_CURRENT_WORKSPACE");
  const firstStop = runHook("stop", { session_id: `orphan-stop-${suffix}` }), secondStop = runHook("stop", { session_id: `orphan-stop-${suffix}` }); assert.equal(firstStop.stopReason, "RECOVERY_REQUIRED"); assert.equal(firstStop.systemMessage, "RECOVERY_REQUIRED:RESUME_CURRENT_WORKSPACE"); assert.deepEqual(secondStop, firstStop); assert.equal(loadState(`orphan-stop-${suffix}`).stallCount, 0);

  const beforeWorktrees = gitAt(fixture, "worktree", "list", "--porcelain"), beforeBranch = gitAt(fixture, "branch", "--show-current"), recovered = automatic(runHook("user-prompt", { session_id: orphanSession, prompt: "RESUME_CURRENT_WORKSPACE" })), taskId = recovered.boundTaskId;
  assert.equal(recovered.promptDisposition, "RESUME_CURRENT_WORKSPACE"); assert.equal(recovered.recoveredWorkspace.pr, 999); assert.equal(loadState(orphanSession).boundTaskId, taskId); assert.equal(gitAt(fixture, "branch", "--show-current"), beforeBranch); assert.equal(gitAt(fixture, "worktree", "list", "--porcelain"), beforeWorktrees); assert.equal(loadTask(taskId).recovery.intent, "RESUME_CURRENT_WORKSPACE");

  const businessBefore = taskFiles(taskId), revisionBefore = loadTask(taskId).revision, promptOnlySession = `prompt-only-${suffix}`, status = automatic(runHook("user-prompt", { session_id: promptOnlySession, prompt: "what is the status" })); assert.equal(status.boundTaskId, taskId); assert.equal(status.promptDisposition, "STATUS"); assert.equal(loadTask(taskId).revision, revisionBefore); assert.deepEqual(taskFiles(taskId), businessBefore);
  for (const source of ["resume", "clear", "compact"]) { const resumed = automatic(runHook("session-start", { session_id: `${source}-${suffix}`, source })); assert.equal(resumed.boundTaskId, taskId); assert.equal(loadTask(taskId).revision, revisionBefore); }
  const continued = automatic(runHook("user-prompt", { session_id: `continue-${suffix}`, prompt: "continue" })); assert.equal(continued.boundTaskId, taskId); assert.equal(continued.promptDisposition, "CONTINUATION"); assert.equal(loadTask(taskId).revision, revisionBefore);
  const exact = automatic(runHook("user-prompt", { session_id: `exact-${suffix}`, prompt: `KERNEL_CONTINUE|taskId=${taskId}|status=IMPLEMENTATION_IN_PROGRESS|reason=resume` })); assert.equal(exact.boundTaskId, taskId); assert.equal(loadTask(taskId).revision, revisionBefore);
  const wrongExact = runHook("user-prompt", { session_id: `wrong-exact-${suffix}`, prompt: "KERNEL_CONTINUE|taskId=20990101-does-not-exist|status=x" }); assert.equal(wrongExact.continue, false); assert.match(wrongExact.stopReason, /CONTINUATION_TASK_MISMATCH/);

  writeFileSync(resolve(fixture, "recovery-ahead.txt"), "local ahead\n"); gitAt(fixture, "add", "recovery-ahead.txt"); gitAt(fixture, "commit", "-m", "test: saved local commit ahead of recorded head"); const aheadHead = gitAt(fixture, "rev-parse", "HEAD"); assert.notEqual(aheadHead, loadTask(taskId).headSha);
  const ahead = automatic(runHook("user-prompt", { session_id: `ahead-${suffix}`, prompt: "status" })); assert.equal(ahead.boundTaskId, taskId); assert.equal(loadTask(taskId).headSha, initialHead); assert.equal(loadTask(taskId).revision, revisionBefore);
  writeFileSync(resolve(fixture, "recovery-ahead.txt"), "interrupted tracked work\n"); writeFileSync(resolve(fixture, "interrupted-untracked.txt"), "interrupted untracked work\n"); const dirtyBefore = gitAt(fixture, "status", "--porcelain=v1", "--untracked-files=all"), dirty = automatic(runHook("user-prompt", { session_id: `dirty-${suffix}`, prompt: "resume" })); assert.equal(dirty.boundTaskId, taskId); assert.equal(gitAt(fixture, "status", "--porcelain=v1", "--untracked-files=all"), dirtyBefore); assert.equal(readFileSync(resolve(fixture, "recovery-ahead.txt"), "utf8"), "interrupted tracked work\n"); assert.equal(readFileSync(resolve(fixture, "interrupted-untracked.txt"), "utf8"), "interrupted untracked work\n");
  writeFileSync(resolve(fixture, "recovery-ahead.txt"), "local ahead\n"); rmSync(resolve(fixture, "interrupted-untracked.txt")); assert.equal(gitAt(fixture, "status", "--porcelain=v1", "--untracked-files=all"), "");

  const concurrentId = `concurrent-${suffix}`, concurrentInput = JSON.stringify({ session_id: concurrentId, prompt: `KERNEL_CONTINUE|taskId=${taskId}|status=x` }), children = [0, 1].map(() => spawnSync(process.execPath, ["scripts/engineering/hooks/user-prompt.mjs"], { cwd: fixture, encoding: "utf8", env: process.env, input: concurrentInput })); assert(children.every((child) => child.status === 0 && JSON.parse(child.stdout).hookSpecificOutput)); assert.equal(loadState(concurrentId).boundTaskId, taskId);
  const countBeforeNew = listTasks().length, deniedNew = runHook("user-prompt", { session_id: promptOnlySession, prompt: "NEW_TASK: A completely different requirement text" }); assert.equal(deniedNew.continue, false); assert.match(deniedNew.stopReason, /NEW_TASK_ACTIVE_TASK_EXISTS/); assert.equal(listTasks().length, countBeforeNew);
  const deniedCliNew = spawnSync(process.execPath, ["scripts/engineering/task-controller.mjs", "--task", "A different CLI requirement must not duplicate"], { cwd: fixture, encoding: "utf8", env: process.env }); assert.equal(deniedCliNew.status, 2); assert.match(deniedCliNew.stderr, /NEW_TASK_ACTIVE_TASK_EXISTS/); assert.equal(listTasks().length, countBeforeNew);

  const currentRepository = repositoryIdentity(fixture), current = { ...identity, ...currentRepository, repository: currentRepository }, records = [{ worktree: repository }, { worktree: current.worktree }], otherWorktree = resolve(repository, ".worktrees", "other");
  const checkReason = (reason, options) => assert.equal(inspectWorkspaceSuitability({ current, records, repository, tasks: [], dirty: false, ...options }).reason, reason);
  checkReason("BRANCH_UNSUITABLE", { current: { ...current, branch: "" } }); checkReason("WORKTREE_NOT_REGISTERED", { records: [{ worktree: repository }] }); checkReason("PRIMARY_WORKTREE_UNSUITABLE", { records: [{ worktree: current.worktree }] }); checkReason("WORKTREE_LOCATION_UNSUITABLE", { repository: resolve(repository, "different-root") }); checkReason("WORKTREE_DIRTY_FOR_NEW_TASK", { mode: "new-task", dirty: true });
  checkReason("ACTIVE_TASK_EXISTS", { mode: "new-task", task: "new", tasks: [{ taskId: "active", task: "old", branch: current.branch, worktree: current.worktree }] }); checkReason("TASK_BRANCH_MISMATCH", { mode: "recovery", tasks: [{ taskId: "claim", branch: "fix/other", worktree: current.worktree }] }); checkReason("TASK_WORKTREE_MISMATCH", { mode: "recovery", tasks: [{ taskId: "claim", branch: current.branch, worktree: otherWorktree }] }); checkReason("TASK_RECOVERY_AMBIGUOUS", { mode: "recovery", tasks: [{ taskId: "one", branch: current.branch, worktree: current.worktree }, { taskId: "two", branch: current.branch, worktree: current.worktree }] }); assert.equal(inspectWorkspaceSuitability({ current, records, repository, tasks: [], dirty: true, mode: "recovery" }).suitable, true);
  assert.throws(() => assertTaskCompatibility({ ...loadTask(taskId), branch: "fix/wrong" }, current), /TASK_BRANCH_MISMATCH/); assert.throws(() => assertTaskCompatibility({ ...loadTask(taskId), worktree: otherWorktree }, current), /TASK_WORKTREE_MISMATCH/); assert.throws(() => assertTaskCompatibility({ ...loadTask(taskId), repositoryCommonGitDir: otherWorktree }, current), /TASK_REPOSITORY_MISMATCH/); assert.throws(() => assertTaskCompatibility({ ...loadTask(taskId), headSha: "0".repeat(40) }, current), /TASK_HISTORY_DIVERGED/); if (process.platform === "win32") assert.equal(assertTaskCompatibility({ ...loadTask(taskId), worktree: fixture.toUpperCase(), repositoryCommonGitDir: current.repositoryCommonGitDir.toUpperCase() }, current).taskId, taskId);

  const secondId = `20260905-ambiguous-${suffix}`, currentTaskIdentity = { ...identity, headSha: aheadHead, treeSha: gitAt(fixture, "rev-parse", "HEAD^{tree}") }; createTask({ taskId: secondId, task: "Second compatible unfinished task", identity: currentTaskIdentity, context: newTaskContext }); const ambiguous = runHook("session-start", { session_id: `ambiguous-${suffix}`, source: "startup" }); assert.equal(ambiguous.continue, false); assert.equal(ambiguous.stopReason, "SESSION_BINDING_FAILED:SESSION_BINDING_AMBIGUOUS:2");
  const legacyAmbiguousId = `legacy-ambiguous-${suffix}`; writeFileSync(sessionPath(legacyAmbiguousId), `${JSON.stringify({ schemaVersion: 1, revision: 7 })}\n`); const legacyAmbiguous = runHook("session-start", { session_id: legacyAmbiguousId, source: "resume" }); assert.equal(legacyAmbiguous.continue, false); assert.equal(legacyAmbiguous.stopReason, "SESSION_BINDING_FAILED:SESSION_BINDING_AMBIGUOUS:2");
  complete(taskId); complete(secondId); const terminalExcluded = automatic(runHook("session-start", { session_id: `terminal-${suffix}`, source: "startup" })); assert.equal(terminalExcluded.sessionStatus, "AWAITING_TASK"); assert.equal(terminalExcluded.boundTaskId, null);
  const successor = automatic(runHook("user-prompt", { session_id: `successor-${suffix}`, prompt: "NEW_TASK: Create a bounded successor kernel task" })), successorId = successor.createdTaskId; assert(successorId); assert.notEqual(successorId, taskId); assert.equal(loadState(`successor-${suffix}`).boundTaskId, successorId); complete(successorId);

  const adoptionInputs = ["adopt-a", "adopt-b"].map((name) => ({ name: `${name}-${suffix}`, input: JSON.stringify({ session_id: `${name}-${suffix}`, prompt: "RESUME_CURRENT_WORKSPACE" }) })), adoptionChildren = adoptionInputs.map(({ input }) => spawnSync(process.execPath, ["scripts/engineering/hooks/user-prompt.mjs"], { cwd: fixture, encoding: "utf8", env: process.env, input })); assert(adoptionChildren.every((child) => child.status === 0 && JSON.parse(child.stdout).hookSpecificOutput)); const adoptedIds = adoptionInputs.map(({ name }) => loadState(name).boundTaskId); assert.equal(new Set(adoptedIds).size, 1); complete(adoptedIds[0]);

  const beforeFaultIds = readdirSync(taskRoot).sort(), faultSession = `fault-${suffix}`, fault = runHook("user-prompt", { session_id: faultSession, prompt: "RESUME_CURRENT_WORKSPACE" }, { ...process.env, ZD_OS_FAULT_AFTER_TASK_CREATE: "1" }); assert.equal(fault.continue, false); assert.match(fault.stopReason, /INJECTED_BINDING_WRITE_FAILURE/); assert.deepEqual(readdirSync(taskRoot).sort(), beforeFaultIds); assert.equal(loadState(faultSession).boundTaskId, undefined);
  const taskWriteFaultSession = `task-write-fault-${suffix}`, taskWriteFault = runHook("user-prompt", { session_id: taskWriteFaultSession, prompt: "RESUME_CURRENT_WORKSPACE" }, { ...process.env, ZD_OS_FAULT_DURING_TASK_CREATE: "1" }); assert.equal(taskWriteFault.continue, false); assert.match(taskWriteFault.stopReason, /INJECTED_TASK_WRITE_FAILURE/); assert.deepEqual(readdirSync(taskRoot).sort(), beforeFaultIds); assert.equal(loadState(taskWriteFaultSession).boundTaskId, undefined);

  const coexistSession = `coexist-${suffix}`, projectOnly = runHook("session-start", { session_id: coexistSession, source: "resume" }), withPonytail = runHook("session-start", { session_id: coexistSession, source: "resume" }, { ...process.env, PONYTAIL_ENABLED: "1" }); assert.deepEqual(withPonytail, projectOnly);

  const corruptId = `20260905-corrupt-${suffix}`, corruptPath = resolve(taskRoot, corruptId, "task.json"); mkdirSync(dirname(corruptPath), { recursive: true }); writeFileSync(corruptPath, "{interrupted"); const corrupt = runHook("session-start", { session_id: `corrupt-${suffix}`, source: "startup" }); assert.equal(corrupt.continue, false); assert.match(corrupt.stopReason, /TASK_DISCOVERY_CORRUPT/); assert.equal(readFileSync(corruptPath, "utf8"), "{interrupted");
  const corruptSessionId = `state-corrupt-${suffix}`; mkdirSync(dirname(sessionPath(corruptSessionId)), { recursive: true }); writeFileSync(sessionPath(corruptSessionId), "{broken"); const corruptSession = runHook("user-prompt", { session_id: corruptSessionId, prompt: "status" }); assert.equal(corruptSession.continue, false); assert.match(corruptSession.stopReason, /STATE_CORRUPT/);

  const selfTest = spawnSync(process.execPath, ["scripts/engineering/task-controller.mjs", "--self-test"], { cwd: fixture, encoding: "utf8", env: process.env }); assert.equal(selfTest.status, 0, selfTest.stderr); assert.equal(JSON.parse(selfTest.stdout).code, "CRM_TASK_SELF_TEST_PASS");
  console.log(JSON.stringify({ code: "TASK_CONTINUITY_CHILD_HOOKS_PASS", hooks: ["SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop"], cases: ["prompt-first", "fresh-resumed", "exact-continuation", "local-ahead", "dirty-resume", "new-task-no-duplicate", "workspace-adoption", "structured-reasons", "ambiguity", "terminal-exclusion", "concurrent-cas", "fault-rollback", "corruption", "windows-cmd-transport", "ponytail-coexistence", "saved-commit-fixture"] }));
} finally {
  if (previousTaskRoot === undefined) delete process.env.ZD_OS_STATE_ROOT; else process.env.ZD_OS_STATE_ROOT = previousTaskRoot; if (previousSessionRoot === undefined) delete process.env.ZD_OS_SESSION_ROOT; else process.env.ZD_OS_SESSION_ROOT = previousSessionRoot; if (previousPrFixture === undefined) delete process.env.ZD_OS_RECOVERY_PR_FIXTURE; else process.env.ZD_OS_RECOVERY_PR_FIXTURE = previousPrFixture;
  if (existsSync(fixture)) spawnSync("git", ["-c", "core.hooksPath=", "worktree", "remove", "--force", fixture], { cwd: root, encoding: "utf8", env: gitEnvironmentFor(root) }); spawnSync("git", ["-c", "core.hooksPath=", "branch", "-D", fixtureBranch], { cwd: root, encoding: "utf8", env: gitEnvironmentFor(root) }); for (const path of [taskRoot, sessionRoot]) if (existsSync(path)) removeEngineeringTemp(path);
}
