import fs from "node:fs";
import path from "node:path";
import type { TaskFile } from "./types.js";
import { inspectRepo } from "./git.js";

function readJson<T>(p: string): T {
  return JSON.parse(fs.readFileSync(p, "utf8")) as T;
}

export function compileContext(root: string, task: TaskFile) {
  const wt = task.repository.worktreePath;
  if (!wt) throw new Error("Task has no worktreePath. Repository recovery is required.");

  const repo = inspectRepo(wt);
  const authorities = readJson<any>(path.join(root, ".crm-engineering","knowledge","authority-registry.json"));
  const capabilities = readJson<any>(path.join(root, ".crm-engineering","knowledge","capability-registry.json"));
  const lessons = readJson<any>(path.join(root, ".crm-engineering","knowledge","lessons-registry.json"));

  const selectedAuthorities = authorities.facts.filter((x: any) =>
    task.domains.some(d =>
      JSON.stringify(x).toLowerCase().includes(d.replace(/-/g," ").toLowerCase()) ||
      JSON.stringify(x).toLowerCase().includes(d.replace(/-/g,"_").toLowerCase())
    )
  );

  const selectedCapabilities = capabilities.capabilities.filter((x: any) =>
    x.authorityRefs?.some((r: string) =>
      selectedAuthorities.some((a: any) => a.id === r)
    ) || task.domains.some(d => JSON.stringify(x).toLowerCase().includes(d.split("-")[0]))
  );

  const selectedLessons = lessons.lessons.filter((x: any) =>
    task.domains.some(d => JSON.stringify(x).toLowerCase().includes(d.split("-")[0])) ||
    ["Execution management","Worktree authority","Production safety"].includes(x.domain)
  );

  const remaining = task.acceptance.filter(a => a.required && a.status !== "PASS");

  return [
    "# CRM GRAPH CONTEXT PACKET",
    `TASK: ${task.taskId}`,
    `OBJECTIVE: ${task.objective}`,
    `PHASE: ${task.phase}`,
    `RISK: ${task.risk}`,
    `WORKTREE: ${wt}`,
    `BRANCH: ${repo.branch ?? "DETACHED"}`,
    `HEAD: ${repo.head}`,
    `EXPECTED BASE: ${task.repository.expectedBaseSha ?? task.repository.expectedBaseRef}`,
    "",
    "## Domains",
    ...task.domains.map(x => `- ${x}`),
    "",
    "## Allowed paths",
    ...task.allowedPaths.map(x => `- ${x}`),
    "",
    "## Protected domains",
    ...task.protectedDomains.map(x => `- ${x}`),
    "",
    "## Selected authorities",
    ...selectedAuthorities.map((x:any) => `- ${x.id}: ${x.authority}`),
    "",
    "## Reusable capabilities",
    ...selectedCapabilities.map((x:any) => `- ${x.id}: ${x.status}`),
    "",
    "## Binding lessons",
    ...selectedLessons.map((x:any) => `- ${x.id}: ${x.rule}`),
    "",
    "## Required acceptance remaining",
    ...remaining.map(x => `- ${x.id} [${x.stage}] ${x.description}`),
    "",
    "## Controller contract",
    "- Do not read docs/os or .harness for workflow.",
    "- Do not broaden scope.",
    "- Implementation incomplete is not BLOCKED.",
    "- Broad verification is illegal until implementation acceptance is complete.",
    "- Return structured worker result; controller owns next state."
  ].join("\n");
}

export function writeContextProjection(root: string, task: TaskFile) {
  const packet = compileContext(root, task);
  const p = path.join(root, "CRM_CONTEXT.md");
  fs.writeFileSync(
    p,
    [
      "# CRM_Zero Current Engineering Context",
      "",
      "> Generated by CRM Engineering Graph. Do not hand-edit task state here.",
      "",
      packet
    ].join("\n"),
    "utf8"
  );
  return p;
}
