import { execFileSync } from 'node:child_process'; import { chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs'; import { basename, resolve } from 'node:path';
import { decryptPayload, sha256 } from './crypto.mjs';
import { untarGz } from './tar.mjs';
const root = '/opt/zerodata-migration', etc = '/etc/zerodata-migration', incoming = '/srv/zerodata-migrator/incoming', staging = `${root}/staging`, used = `${etc}/used-nonces`;
const fail = (code) => { throw new Error(code); };
const json = (path) => JSON.parse(readFileSync(path, 'utf8'));
export function validateUploadName(name) { if (!/^[a-f0-9]{64}\.zdp$|^request\.json$/i.test(name)) fail('OPERATOR_EXECUTABLE_UPLOAD_REJECTED'); return true; }
export function revokeOperatorWrite(incomingDir = incoming) { chmodSync(incomingDir, 0o750); return 'POST_MIGRATION_OPERATOR_WRITE_REVOKED'; }
export function authorize({ payload, request, job, installed = job }) { const hash = sha256(readFileSync(payload)); if (installed.packageSha256 !== job.packageSha256 || installed.repositorySha !== job.repositorySha) fail('PACKAGE_PROVENANCE_INVALID'); if (request.packageSha256 !== job.packageSha256 || request.payloadCiphertextSha256 !== hash || request.sourceSnapshotId !== job.sourceSnapshotId || request.repositorySha !== job.repositorySha) fail('PAYLOAD_NOT_AUTHORIZED'); if (Date.parse(job.expiresAt) <= Date.now()) fail('PAYLOAD_EXPIRED'); if (existsSync(resolve(used, job.oneTimeNonce))) fail('MIGRATION_PAYLOAD_REPLAY_DENIED'); return hash; }
export async function run() {
  validateUploadName(basename(process.argv[2] ?? ''));
  const request = resolve(incoming, 'request.json'), job = json(`${etc}/authorized-job.json`);
  if (!existsSync(request)) fail('PAYLOAD_NOT_AUTHORIZED');
  const requestBody = json(request), candidates = readdirSync(incoming).filter((name) => /^[a-f0-9]{64}\.zdp$/i.test(name)).map((name) => resolve(incoming, name)).filter((path) => sha256(readFileSync(path)) === requestBody.payloadCiphertextSha256);
  if (candidates.length !== 1) fail('PAYLOAD_NOT_AUTHORIZED');
  const payload = candidates[0], installed = json(`${etc}/installed-package.json`), ciphertextSha256 = authorize({ payload, request: requestBody, job, installed }); mkdirSync(staging, { recursive: true, mode: 0o700 }); const accepted = resolve(staging, `${job.oneTimeNonce}.zdp`); renameSync(payload, accepted); renameSync(request, resolve(staging, `${job.oneTimeNonce}.request.json`)); const plaintext = resolve(staging, `${job.oneTimeNonce}.tar.gz`); const header = await decryptPayload({ input: accepted, output: plaintext, privateKeyPem: readFileSync(`${etc}/migration-private.pem`, 'utf8') }); const innerManifest = untarGz(readFileSync(plaintext)).get('manifest.json'); if (!innerManifest || sha256(innerManifest) !== header.plaintextManifestSha256) fail('PACKAGE_PROVENANCE_INVALID'); const manifest = JSON.parse(innerManifest); if (header.sourceSnapshotId !== job.sourceSnapshotId || header.repositorySha !== job.repositorySha || manifest.sourceSnapshotId !== job.sourceSnapshotId || manifest.repositorySha !== job.repositorySha) fail('PACKAGE_VERSION_MISMATCH'); mkdirSync(used, { recursive: true, mode: 0o700 }); writeFileSync(resolve(used, job.oneTimeNonce), `${ciphertextSha256}\n`, { mode: 0o600 }); chmodSync(resolve(used, job.oneTimeNonce), 0o600); execFileSync(`${root}/restore-target.sh`, [plaintext, job.oneTimeNonce], { stdio: 'inherit' }); revokeOperatorWrite(); console.log(JSON.stringify({ status: 'ZERODATA_MIGRATION_CERTIFIED', sourceSnapshotId: header.sourceSnapshotId, repositorySha: header.repositorySha }));
}
if (process.argv[1] === new URL(import.meta.url).pathname) run().catch((error) => { console.error(error.message); process.exitCode = 1; });
