"use client";
import {useCallback,useEffect,useState} from "react";import Link from "next/link";import {Building2} from "lucide-react";import {supabase} from "@/lib/supabaseClient";import type {DistributorStatusRow} from "@/lib/distributors/types";import {renewalLabel} from "@/lib/distributors/domain";import {PageHeader} from "@/components/ui/PageHeader";import {Button} from "@/components/ui/Button";import {Chip} from "@/components/ui/Chip";
import {RenewalEditorModal} from "@/components/distributors/RenewalEditorModal";
export default function AssignedDistributorStatusPage(){const [rows,setRows]=useState<DistributorStatusRow[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[message,setMessage]=useState("");
const [editingId,setEditingId]=useState<string|null>(null);
const authFetch=useCallback(async(url:string,init?:RequestInit)=>{const {data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("Sign in again.");return fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers,Authorization:`Bearer ${data.session.access_token}`},cache:"no-store"})},[]);
const load=useCallback(async()=>{try{const response=await authFetch(`/api/distributors/renewals?limit=50`),result=await response.json();if(!response.ok)throw new Error(result.message??"Distributor Status unavailable.");setRows(result.rows);setTotal(result.total)}catch(e){setMessage(e instanceof Error?e.message:"Error loading renewals.");}},[authFetch]);
useEffect(()=>{void load()},[load]);return <div className="px-6 pb-6"><PageHeader eyebrow="Operational Reminders" icon={<Building2 size={16}/>} title="Renewals Due" description="Actionable upcoming and overdue distributor renewals." />{message&&<div className="alert-panel alert-panel--info">{message}</div>}<div className="grid gap-3">{rows.map(row=><article key={row.distributor_id} className="surface-panel p-4 cursor-pointer hover:bg-neutral-50 transition-colors" onClick={()=>setEditingId(row.distributor_id)}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{row.distributor_name}</h2><p className="text-xs text-[var(--text-muted)]">Renewal {row.renewal_date??"not set"}</p></div><div className="flex flex-wrap gap-2"><Chip variant={row.renewal_state==="renewal_overdue"?"danger":row.renewal_state.includes("due")?"warning":"neutral"}>{renewalLabel(row.renewal_state)}</Chip></div></div></article>)}{!rows.length&&!message&&<p className="text-sm text-[var(--text-muted)]">No renewals are due.</p>}</div><div className="flex justify-between mt-4"><span>{total} actionable renewals</span></div>
<RenewalEditorModal open={editingId!==null} distributorId={editingId} authFetch={authFetch} onClose={()=>setEditingId(null)} onSave={()=>{setEditingId(null);setMessage("Renewal saved successfully.");void load();}}/>
</div>}
