import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { assertDeepInventoryBudget, assertRedacted, classifyBudget, compareManifests, evaluateOwnerGate, migrationBoundary, requiredCapabilities, sha256, sourceIdentity, supabaseArgv, validateMigrationBoundary } from './lib.mjs';
import { makeEngineeringTemp, removeEngineeringTemp } from '../engineering/managed-paths.mjs';

const root = process.cwd();
const read = (path) => readFileSync(resolve(root, path), 'utf8');
const inventorySql = read('scripts/handover/inventory.sql');
const docs = read('docs/handover/README.md');
const gates = JSON.parse(read('docs/handover/owner-gates.json'));
const ownerAccess = JSON.parse(read('docs/handover/owner-access-checklist.json'));
const sourceBaseline = JSON.parse(read('docs/handover/source-baseline.json'));
const advisorBaseline = JSON.parse(read('docs/handover/source-advisor-baseline.json'));
const consistency = JSON.parse(read('docs/handover/consistency-contract.json'));
const rehearsalTarget = JSON.parse(read('docs/handover/rehearsal-target.json'));
const domains = JSON.parse(read('docs/engineering/DOMAIN_MAP.json')).domains;
const engineeringCapabilities = JSON.parse(read('docs/engineering/CAPABILITIES.json')).capabilities;
const proofs = JSON.parse(read('docs/engineering/PROOFS.json')).proofs;
const tracked = execFileSync('git', ['ls-files'], { cwd: root, encoding: 'utf8' }).split(/\r?\n/).filter(Boolean);
const vercel = JSON.parse(read('vercel.json'));
const capabilities = Object.fromEntries(requiredCapabilities.map((key) => [key, true]));

function legacyVercelGuard(config) {
  const legacyHash = 'f23c928aebeabcde32d01f4208130156a6cbfe5c7beeb799a942adf8e9474953';
  for (const section of [config.env ?? {}, config.build?.env ?? {}]) for (const [key, value] of Object.entries(section)) {
    if (key === 'SUPABASE_SERVICE_ROLE_KEY' || (/supabase\.co/i.test(String(value)) && key !== 'NEXT_PUBLIC_SUPABASE_URL') || (/SUPABASE_(?:ANON|SERVICE_ROLE)_KEY/i.test(key) && key !== 'NEXT_PUBLIC_SUPABASE_ANON_KEY')) return false;
  }
  const env = config.env ?? {}, build = config.build?.env ?? {};
  return env.NEXT_PUBLIC_SUPABASE_URL === 'https://gwfjkpsoaoherntwhdyf.supabase.co' && build.NEXT_PUBLIC_SUPABASE_URL === env.NEXT_PUBLIC_SUPABASE_URL && sha256(env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '') === legacyHash && build.NEXT_PUBLIC_SUPABASE_ANON_KEY === env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
}

assert.match(inventorySql.trim(), /^begin read only;[\s\S]*commit;$/i);
assert.doesNotMatch(inventorySql, /\b(?:insert|update|delete|alter|create|drop|grant|revoke|truncate)\b/i);
assert.match(read('.gitignore'), /^\.handover\/$/m);
const currentBoundary = migrationBoundary(root);
assert.deepEqual(validateMigrationBoundary({ lastAppliedOwnerMigration: 7, immutableThrough: 7 }), { lastAppliedOwnerMigration: 7, immutableThrough: 7 });
assert.equal(currentBoundary.lastAppliedOwnerMigration, currentBoundary.immutableThrough);
assert.throws(() => sourceIdentity(), /HANDOVER_SOURCE_IDENTITY_UNRESOLVED/);
assert.throws(() => sourceIdentity('postgres://x@db.other.supabase.co/postgres'), /HANDOVER_SOURCE_IDENTITY_UNRESOLVED/);
assert.equal(sourceIdentity('postgresql://x@db.gwfjkpsoaoherntwhdyf.supabase.co:5432/postgres').endpoint, 'direct-db-host');
assert.equal(sourceIdentity('postgresql://postgres.gwfjkpsoaoherntwhdyf:x@aws-0-ap-south-1.pooler.supabase.com:5432/postgres').endpoint, 'session-pooler');
assert.throws(() => sourceIdentity('postgresql://postgres.other:x@aws-0-ap-south-1.pooler.supabase.com/postgres'), /HANDOVER_SOURCE_IDENTITY_UNRESOLVED/);
assert.deepEqual(supabaseArgv(['functions', 'list']), ['supabase', 'functions', 'list']);
assert.throws(() => supabaseArgv(['supabase', 'functions', 'list']), /HANDOVER_SUPABASE_ARGV_INVALID/);
assert.deepEqual([classifyBudget(49, 100), classifyBudget(50, 100), classifyBudget(70, 100), classifyBudget(71, 100)], ['GREEN', 'YELLOW', 'YELLOW', 'RED']);
assert.doesNotThrow(() => assertDeepInventoryBudget(10, 20));
assert.throws(() => assertDeepInventoryBudget(21, 20), /HANDOVER_DEEP_INVENTORY_BUDGET_EXCEEDED/);
assert.throws(() => assertDeepInventoryBudget(400_000_000, 500_000_000), /HANDOVER_DEEP_INVENTORY_BUDGET_EXCEEDED/);
const inventoryScript = read('scripts/handover/inventory.mjs');
assert.match(inventoryScript, /vault\.secrets/);
assert.match(inventoryScript, /edgeFunctionSecretCount/);
for (const token of ['columns','enumLabels','pg_get_constraintdef','pg_get_indexdef','pg_get_viewdef','pg_get_functiondef','pg_get_triggerdef','usingHash','withCheckHash','routine_privileges','pg_default_acl','applicationPublicationTables','commandHash','payloadBytes']) assert.match(inventorySql, new RegExp(token));
assert.match(inventorySql, /set local statement_timeout='60s'/i);
assert.match(inventorySql, /set local lock_timeout='5s'/i);
assert.match(inventorySql, /authUsersApplicationTriggers/);
assert.throws(() => assertRedacted({ note: 'person@example.com' }), /SENSITIVE_VALUE/);
assert.throws(() => assertRedacted({ note: 'postgresql://secret' }), /SENSITIVE_VALUE/);
assert.throws(() => assertRedacted({ note: 'eyJabc.def.ghi' }), /SENSITIVE_VALUE/);
assert.doesNotThrow(() => assertRedacted({ definitionHash: sha256('safe') }));
assert.equal(legacyVercelGuard(vercel), true);
assert.equal(legacyVercelGuard({ env: { NEXT_PUBLIC_SUPABASE_URL: 'https://new.supabase.co' }, build: { env: {} } }), false);
assert.equal(tracked.some((path) => /(?:^|\/)(?:roles|data)\.sql$|(?:^|\/)source-inventory\.json$|(?:^|\/)SHA256SUMS$/.test(path) || (path.endsWith('/schema.sql') && path !== 'supabase/schema.sql')), false, 'tracked handover artifact leak');

assert.deepEqual(gates.gates.map(({ id }) => id), ['G0', 'G1', 'G2', 'G3', 'G4']);
assert.equal(gates.agentApprovalSynthesisProhibited, true);
assert.equal(gates.gates.find(({ id }) => id === 'G1').status, 'MANUAL_OWNER_EVIDENCE_REQUIRED');
assert.equal(gates.gates.find(({ id }) => id === 'G2').grantsProductionAuthority, false);
assert.ok(gates.gates.find(({ id }) => id === 'G2').requires.includes('SOURCE_SNAPSHOT_BOUND'));
assert.equal(gates.gates.find(({ id }) => id === 'G3').permitsSourceDecommission, false);
for (const prerequisite of ['SOURCE_SNAPSHOT_BOUND', 'CUTOVER_WRITERS_QUIESCED', 'CLIENT_CUTOVER_COMPATIBILITY_PROVEN', 'FINAL_STORAGE_DELTA_CERTIFIED', 'SOURCE_ROLLBACK_AVAILABILITY_PLAN', 'VERCEL_ENV_HANDOFF_REQUIRED satisfied', 'OWNER_ACCESS_CHECKLIST satisfied']) assert.ok(gates.gates.find(({ id }) => id === 'G3').prerequisites.includes(prerequisite));
assert.equal(gates.gates.find(({ id }) => id === 'G4').independentOf, 'G3');
assert.equal(ownerAccess.defaultStatus, 'MANUAL_OWNER_EVIDENCE_REQUIRED');
assert.equal(ownerAccess.valuesRecorded, false);
assert.equal(sourceBaseline.projectRef, 'gwfjkpsoaoherntwhdyf');
assert.equal(sourceBaseline.sourceStatus, 'ACTIVE_HEALTHY');
assert.equal(sourceBaseline.freshInventoryOverrides, true);
assert.equal(advisorBaseline.classification, 'SOURCE_BASELINE');
assert.equal(advisorBaseline.sanitized, true);
assert.equal(advisorBaseline.futureHardening, 'SEPARATE_OWNER_APPROVED_R3_TASK');
assert.doesNotThrow(() => assertRedacted(advisorBaseline));
assert.deepEqual(consistency.states, ['LIVE_BULK_COPY', 'SNAPSHOT_BOUND', 'WRITE_QUIESCED_FINAL', 'DELTA_RECONCILED']);
assert.ok(consistency.cutover.writers.includes('offline queues/recovery'));
assert.ok(consistency.cutover.requiredClientEvidence.includes('OFFLINE_QUEUE_CUTOVER_CONVERGENCE_REQUIRED'));
assert.deepEqual(consistency.storage.phases, ['BULK_STORAGE_COPY', 'FINAL_STORAGE_DELTA']);
assert.equal(consistency.rollback.safeDefault, 'KEEP_MANAGED_SOURCE_ACTIVE');
assert.equal(rehearsalTarget.status, 'NOT_CREATED');
assert.equal(rehearsalTarget.providerDecision, 'G1_OWNER_DECISION_REQUIRED');
assert.ok(rehearsalTarget.requirements.includes('default Envoy gateway unless supported Kong compatibility is proven'));
assert.equal(evaluateOwnerGate('G2'), 'SOURCE_SNAPSHOT_UNBOUND');
assert.equal(evaluateOwnerGate('G2', { sourceSnapshotBound: true }), 'FINAL_STORAGE_DELTA_NOT_CERTIFIED');
assert.equal(evaluateOwnerGate('G3'), 'CUTOVER_WRITERS_NOT_QUIESCED');
assert.equal(evaluateOwnerGate('G3', { writersQuiesced: true }), 'CLIENT_CUTOVER_COMPATIBILITY_NOT_RUN');
assert.equal(evaluateOwnerGate('G3', { writersQuiesced: true, clientCutoverCompatibilityProven: true }), 'SOURCE_ROLLBACK_AVAILABILITY_PLAN');

const handoverDomain = domains.find(({ id }) => id === 'platform-handover');
const handoverCapability = engineeringCapabilities.find(({ id }) => id === 'supabase-handover-certification');
const handoverProof = proofs.find(({ id }) => id === 'supabase-handover-readiness');
assert.equal(handoverDomain.riskFloor, 'R3');
assert.ok(handoverDomain.proofRefs.includes('supabase-handover-readiness'));
assert.equal(handoverCapability.status, 'ACTIVE');
assert.deepEqual(handoverProof, { id: 'supabase-handover-readiness', kind: 'handover', domains: ['platform-handover'], effects: ['PLATFORM','DATABASE','AUTHORIZATION','SECURITY','STORAGE','REALTIME','CONFIGURATION'], runner: 'node', paths: ['scripts/handover/check.mjs'] });

const fingerprint = sha256('certified');
const base = { manifestVersion: 2, capabilities, edgeFunctionCount: 0, vaultSecretCount: 0, snapshotConsistency: { state: 'SNAPSHOT_BOUND', snapshotId: fingerprint, dumpArtifactSha256: fingerprint }, semantic: { application: { tables: [{ table: 'x' }] }, types: [1], constraints: [], indexes: [], views: [], functions: [], triggers: [], policies: [], privileges: {} }, realtime: { applicationPublicationTables: ['x'] }, deepData: { public: { x: { fingerprint } }, auth: { userUuidSet: fingerprint, identitySet: fingerprint, credentialSet: fingerprint } }, storage: { bucketConfiguration: [], fullIntegrity: { status: 'CERTIFIED', bulkCopyStatus: 'CERTIFIED', finalDeltaStatus: 'CERTIFIED', expectedObjectCount: 1, verifiedObjectCount: 1, expectedBytes: 1, verifiedBytes: 1, mismatchCount: 0, aggregateFingerprint: fingerprint } }, businessInvariants: { x: 1 }, inventory: { database: { bytes: 1 }, cron: [{ jobid: 1, jobname: 'nightly', schedule: '0 1 * * *', active: true, commandHash: fingerprint, classification: 'NORMAL' }], extensions: [{ extension: 'pg_cron', version: '1.6' }], managedHooks: { authUsersApplicationTriggers: [{ trigger: 'app_auth', enabled: 'O', definitionHash: fingerprint }] } } };
assert.equal(compareManifests(base, structuredClone(base)).status, 'HANDOVER_PARITY_PASS');
assert.equal(compareManifests({ ...base, deepData: {} }, structuredClone(base)).status, 'HANDOVER_CERTIFICATION_INCOMPLETE');
assert.equal(compareManifests({ ...base, deepData: { ...base.deepData, auth: {} } }, structuredClone(base)).status, 'HANDOVER_CERTIFICATION_INCOMPLETE');
assert.equal(compareManifests({ ...base, storage: { ...base.storage, fullIntegrity: { status: 'PENDING' } } }, structuredClone(base)).status, 'HANDOVER_CERTIFICATION_INCOMPLETE');
assert.equal(compareManifests({ ...base, storage: { ...base.storage, fullIntegrity: { status: 'CERTIFIED' } } }, structuredClone(base)).status, 'HANDOVER_CERTIFICATION_INCOMPLETE');
assert.equal(compareManifests({ ...base, storage: { ...base.storage, fullIntegrity: { ...base.storage.fullIntegrity, mismatchCount: 1 } } }, structuredClone(base)).status, 'HANDOVER_CERTIFICATION_INCOMPLETE');
assert.equal(compareManifests(base, { ...structuredClone(base), semantic: { ...base.semantic, types: [2] } }).status, 'HANDOVER_PARITY_FAILED');
assert.equal(compareManifests(base, { ...structuredClone(base), semantic: { ...base.semantic, policies: [2] } }).status, 'HANDOVER_PARITY_FAILED');
assert.equal(compareManifests(base, { ...structuredClone(base), capabilities: { postgresql17: true } }).status, 'TARGET_PLATFORM_INCOMPATIBLE');
assert.equal(compareManifests(base, { ...structuredClone(base), snapshotConsistency: { state: 'LIVE_BULK_COPY' } }).status, 'SOURCE_SNAPSHOT_UNBOUND');
const targetWithoutCron = structuredClone(base); targetWithoutCron.inventory.cron = [];
assert.equal(compareManifests(base, targetWithoutCron).status, 'HANDOVER_CRON_PARITY_FAILED');
const targetCronCommandDrift = structuredClone(base); targetCronCommandDrift.inventory.cron[0].commandHash = sha256('changed');
assert.equal(compareManifests(base, targetCronCommandDrift).status, 'HANDOVER_CRON_PARITY_FAILED');
const targetCronScheduleDrift = structuredClone(base); targetCronScheduleDrift.inventory.cron[0].schedule = '0 2 * * *';
assert.equal(compareManifests(base, targetCronScheduleDrift).status, 'HANDOVER_CRON_PARITY_FAILED');
const targetWithoutExtension = structuredClone(base); targetWithoutExtension.inventory.extensions = [];
assert.equal(compareManifests(base, targetWithoutExtension).status, 'TARGET_EXTENSION_MISSING');
const targetDifferentExtension = structuredClone(base); targetDifferentExtension.inventory.extensions[0].version = '1.7';
assert.equal(compareManifests(base, targetDifferentExtension).status, 'TARGET_EXTENSION_COMPATIBILITY_UNRESOLVED');
targetDifferentExtension.extensionCompatibility = [{ extension: 'pg_cron', sourceVersion: '1.6', targetVersion: '1.7', status: 'COMPATIBLE', evidenceHash: fingerprint }];
assert.equal(compareManifests(base, targetDifferentExtension).status, 'HANDOVER_PARITY_PASS');
const targetWithoutAuthTrigger = structuredClone(base); targetWithoutAuthTrigger.inventory.managedHooks.authUsersApplicationTriggers = [];
assert.equal(compareManifests(base, targetWithoutAuthTrigger).status, 'HANDOVER_MANAGED_AUTH_TRIGGER_PARITY_FAILED');
assert.equal(compareManifests({ ...base, edgeFunctionCount: 1 }, structuredClone(base)).status, 'HANDOVER_EDGE_FUNCTION_EVIDENCE_REQUIRED');
assert.equal(compareManifests({ ...base, vaultSecretCount: 1 }, structuredClone(base)).status, 'HANDOVER_VAULT_EVIDENCE_REQUIRED');
const storageWithoutFinalDelta = structuredClone(base); storageWithoutFinalDelta.storage.fullIntegrity.finalDeltaStatus = 'PENDING';
assert.equal(compareManifests(base, storageWithoutFinalDelta).status, 'HANDOVER_CERTIFICATION_INCOMPLETE');
const volatileTarget = structuredClone(base); volatileTarget.inventory.database.bytes = 9; volatileTarget.inventory.cron[0].jobid = 99;
assert.equal(compareManifests(base, volatileTarget).status, 'HANDOVER_PARITY_PASS');

const temp = makeEngineeringTemp('handover-check');
writeFileSync(join(temp, 'artifact'), 'one');
const sum = sha256(readFileSync(join(temp, 'artifact')));
assert.equal(sum, sha256('one'));
writeFileSync(join(temp, 'artifact'), 'two');
assert.notEqual(sum, sha256(readFileSync(join(temp, 'artifact'))));
removeEngineeringTemp(temp);
for (const phrase of ['FULL object integrity', 'MANUAL_DASHBOARD_EVIDENCE', 'VERCEL_ENV_HANDOFF_REQUIRED', 'TARGET_PLATFORM_INCOMPATIBLE', 'EXPECTED_REAUTHENTICATION', 'platform-policies.sql', 'encrypted', 'Owner gates', 'SOURCE_BASELINE', 'ROLLBACK_WRITE_RECONCILIATION_REQUIRED']) assert.match(docs, new RegExp(phrase, 'i'));
console.log('HANDOVER_CHECK_PASS');
