begin read only;
set local timezone='UTC';
select jsonb_build_object(
  'database', jsonb_build_object('postgresVersion',current_setting('server_version'),'timezone',current_setting('TimeZone'),'bytes',pg_database_size(current_database())),
  'semantic', jsonb_build_object(
    'application', jsonb_build_object(
      'tables',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'replicaIdentity',c.relreplident) order by c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'),
      'columns',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'column',a.attname,'ordinal',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'underlyingType',a.atttypid::regtype::text,'nullable',not a.attnotnull,'defaultHash',encode(digest(coalesce(pg_get_expr(ad.adbin,ad.adrelid),''),'sha256'),'hex'),'identity',a.attidentity,'generated',a.attgenerated,'collation',coalesce(coll.collname,'')) order by c.relname,a.attnum),'[]') from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum left join pg_collation coll on coll.oid=a.attcollation where n.nspname='public' and c.relkind='r' and a.attnum>0 and not a.attisdropped),
      'tableFingerprint',(select encode(digest(coalesce(string_agg(c.relname||':'||c.relreplident||':'||c.relrowsecurity::text||':'||c.relforcerowsecurity::text,'|' order by c.relname),''),'sha256'),'hex') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r')
    ),
    'types',(select coalesce(jsonb_agg(jsonb_build_object('type',t.typname,'kind',t.typtype,'enumLabels',coalesce(e.labels,'[]'::jsonb),'domainBaseType',coalesce(format_type(t.typbasetype,null),''),'domainNotNull',t.typnotnull,'domainDefaultHash',encode(digest(coalesce(t.typdefault,''),'sha256'),'hex'),'compositeAttributes',coalesce(a.attributes,'[]'::jsonb),'definitionHash',encode(digest(coalesce(pg_catalog.format_type(t.oid,null),''),'sha256'),'hex')) order by t.typname),'[]') from pg_type t join pg_namespace n on n.oid=t.typnamespace left join lateral (select jsonb_agg(enumlabel order by enumsortorder) labels from pg_enum where enumtypid=t.oid) e on true left join lateral (select jsonb_agg(jsonb_build_object('column',attname,'ordinal',attnum,'type',format_type(atttypid,atttypmod),'nullable',not attnotnull) order by attnum) attributes from pg_attribute where attrelid=t.typrelid and attnum>0 and not attisdropped) a on true where n.nspname='public' and t.typtype in ('e','d','c')),
    'constraints',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'constraint',con.conname,'type',con.contype,'validated',con.convalidated,'deferrable',con.condeferrable,'deferred',con.condeferred,'definitionHash',encode(digest(pg_get_constraintdef(con.oid,true),'sha256'),'hex')) order by c.relname,con.conname),'[]') from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'),
    'indexes',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'index',i.relname,'unique',x.indisunique,'primary',x.indisprimary,'valid',x.indisvalid,'ready',x.indisready,'definitionHash',encode(digest(pg_get_indexdef(i.oid),'sha256'),'hex')) order by c.relname,i.relname),'[]') from pg_index x join pg_class i on i.oid=x.indexrelid join pg_class c on c.oid=x.indrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'),
    'views',(select coalesce(jsonb_agg(jsonb_build_object('view',c.relname,'owner',pg_get_userbyid(c.relowner),'definitionHash',encode(digest(pg_get_viewdef(c.oid,true),'sha256'),'hex'),'reloptions',coalesce(to_jsonb(c.reloptions),'[]'::jsonb),'aclHash',encode(digest(coalesce(c.relacl::text,''),'sha256'),'hex')) order by c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('v','m')),
    'functions',(select coalesce(jsonb_agg(jsonb_build_object('function',p.proname,'signature',pg_get_function_identity_arguments(p.oid),'definitionHash',encode(digest(pg_get_functiondef(p.oid),'sha256'),'hex'),'securityDefiner',p.prosecdef,'owner',pg_get_userbyid(p.proowner),'volatility',p.provolatile,'configHash',encode(digest(coalesce(p.proconfig::text,''),'sha256'),'hex'),'aclHash',encode(digest(coalesce(p.proacl::text,''),'sha256'),'hex')) order by p.proname,pg_get_function_identity_arguments(p.oid)),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'),
    'triggers',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'trigger',t.tgname,'enabled',t.tgenabled,'definitionHash',encode(digest(pg_get_triggerdef(t.oid,true),'sha256'),'hex')) order by c.relname,t.tgname),'[]') from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal),
    'policies',(select coalesce(jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'policy',policyname,'permissive',permissive,'command',cmd,'roles',roles,'usingHash',encode(digest(coalesce(qual,''),'sha256'),'hex'),'withCheckHash',encode(digest(coalesce(with_check,''),'sha256'),'hex')) order by schemaname,tablename,policyname),'[]') from pg_policies where schemaname in ('public','storage','realtime')),
    'privileges',jsonb_build_object('tables',(select coalesce(jsonb_agg(jsonb_build_object('table',table_name,'grantee',grantee,'privilege',privilege_type) order by table_name,grantee,privilege_type),'[]') from information_schema.role_table_grants where table_schema='public'),'functions',(select coalesce(jsonb_agg(jsonb_build_object('function',routine_name,'grantee',grantee,'privilege',privilege_type) order by routine_name,grantee),'[]') from information_schema.routine_privileges where specific_schema='public'),'sequences',(select coalesce(jsonb_agg(jsonb_build_object('sequence',object_name,'grantee',grantee,'privilege',privilege_type) order by object_name,grantee),'[]') from information_schema.usage_privileges where object_schema='public' and object_type='SEQUENCE'),'schemas',(select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'aclHash',encode(digest(coalesce(n.nspacl::text,''),'sha256'),'hex')) order by n.nspname),'[]') from pg_namespace n where n.nspname='public'),'defaultPrivileges',(select coalesce(jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'objectType',d.defaclobjtype,'aclHash',encode(digest(coalesce(d.defaclacl::text,''),'sha256'),'hex')) order by 1,2),'[]') from pg_default_acl d join pg_namespace n on n.oid=d.defaclnamespace where n.nspname='public'))
  ),
  'realtime',jsonb_build_object('applicationPublicationTables',(select coalesce(jsonb_agg(tablename order by tablename),'[]') from pg_publication_tables where pubname='supabase_realtime' and schemaname='public'),'managedApplicationPolicies',(select coalesce(jsonb_agg(policyname order by policyname),'[]') from pg_policies where schemaname='realtime' and tablename='messages')),
  'managedHooks',jsonb_build_object('authUsersApplicationTriggerCount',(select count(*) from pg_trigger where tgrelid='auth.users'::regclass and not tgisinternal),'storageApplicationPolicyCount',(select count(*) from pg_policies where schemaname='storage'),'realtimeApplicationPolicyCount',(select count(*) from pg_policies where schemaname='realtime' and tablename='messages')),
  'cron',(select coalesce(jsonb_agg(jsonb_build_object('job',jobname,'schedule',schedule,'active',active,'commandHash',encode(digest(command,'sha256'),'hex'),'classification',case when command ilike '%daily_kpi_snapshots%' then 'KNOWN_LIVE_DEFECT' else 'NORMAL' end) order by jobname),'[]') from cron.job),
  'extensions',(select coalesce(jsonb_agg(jsonb_build_object('extension',extname,'version',extversion) order by extname),'[]') from pg_extension),
  'auth',jsonb_build_object('userCount',(select count(*) from auth.users),'identityProviders',(select coalesce(jsonb_agg(jsonb_build_object('provider',provider,'count',count) order by provider),'[]') from (select provider,count(*) from auth.identities group by provider) q),'schemaMigrationVersion',(select max(version)::text from auth.schema_migrations)),
  'storage',jsonb_build_object('buckets',(select coalesce(jsonb_agg(jsonb_build_object('bucket',id,'public',public,'fileSizeLimit',file_size_limit,'allowedMimeTypes',allowed_mime_types) order by id),'[]') from storage.buckets),'objectCount',(select count(*) from storage.objects),'objectBytes',(select coalesce(sum((metadata->>'size')::bigint),0) from storage.objects),'metadataFingerprint',(select encode(digest(coalesce(string_agg(encode(digest(bucket_id||':'||name||':'||coalesce(metadata::text,''),'sha256'),'hex'),'|' order by bucket_id,name),''),'sha256'),'hex') from storage.objects)),
  'criticalRows',jsonb_build_object('distributorAccounts',(select count(*) from public.distributor_accounts),'receivables',(select count(*) from public.receivables),'receivablePayments',(select count(*) from public.receivable_payments),'calls',(select count(*) from public.call_logs),'fieldVisits',(select count(*) from public.field_visits),'attendance',(select count(*) from public.attendance),'leads',(select count(*) from public.leads),'chatMessages',(select count(*) from public.chat_messages),'fieldVisitMedia',(select count(*) from public.field_visit_media)),
  'financialAggregates',jsonb_build_object('billed',(select coalesce(sum(bill_amount),0) from public.receivables),'confirmedPayments',(select coalesce(sum(amount) filter(where verification_status='confirmed'),0) from public.receivable_payments),'outstanding',(select coalesce(sum(outstanding_amount),0) from public.receivables_financial_read_v1)),
  'fieldVisitMedia',jsonb_build_object('relationBytes',pg_total_relation_size('public.field_visit_media'),'payloadBytes',(select coalesce(sum(octet_length(media_data)),0) from public.field_visit_media))
) as inventory;
commit;
