import { readdirSync, statSync, writeFileSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { configPath, normalize, readJson, root } from "./common.mjs";

function walk(dir) {
  const result = [];
  for (const name of readdirSync(dir).sort()) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) result.push(...walk(path)); else result.push(normalize(relative(root, path)));
  }
  return result;
}
const config = readJson(configPath);
const apiRoutes = walk(join(root, "src/app/api")).filter((p) => /\/route\.(ts|js)$/.test(p));
const lines = ["# Generated Repository Map", "", "Generated by `npm run harness:repo-map`. Safe structural metadata only.", "", "## Domains", "", "| Domain | Criticality | Code paths | Contract |", "|---|---|---|---|"];
for (const [name, value] of Object.entries(config.domains)) lines.push(`| ${name} | ${value.criticality} | ${value.codePaths.map((p) => `\`${p}\``).join("<br>")} | [contract](../${value.contract.replace(/^docs\//, "")}) |`);
lines.push("", "## Important entry files", "", "- `src/app/layout.tsx`", "- `src/lib/db.ts`", "- `src/lib/supabaseClient.ts`", "- `src/context/AuthContext.tsx`", "", "## API routes", "");
for (const route of apiRoutes) lines.push(`- \`${route}\``);
lines.push("", "## Relevant tests", "");
for (const test of [...new Set(Object.values(config.domains).flatMap((d) => d.tests))].sort()) lines.push(`- \`${test}\``);
const output = `${lines.join("\n")}\n`;
const target = join(root, "docs/generated/REPO_MAP.md");
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output) { console.error("Generated repository map is stale. Run npm run harness:repo-map."); process.exit(1); }
} else { writeFileSync(target, output); console.log("Generated docs/generated/REPO_MAP.md"); }
