import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { countWords, globMatch, root } from "./cli.mjs";

const fixtureRoot = path.join(root, "tests", "harness", "fixtures");
const cases = JSON.parse(fs.readFileSync(path.join(fixtureRoot, "cases.json"), "utf8"));
const workflow = fs.readFileSync(path.join(root, ".github", "workflows", "engineering-harness-ci.yml"), "utf8");
const reviewGenerator = fs.readFileSync(path.join(root, "scripts", "harness", "review-pack.mjs"), "utf8");
const results = [];
const assert = (name, condition) => {
  results.push({ name, passed: Boolean(condition) });
  if (!condition) console.error(`FAIL ${name}`);
};
assert("valid scoped change", globMatch("src/lib/db.ts", "src/lib/db.ts"));
assert("changed unrelated file fails", !["src/lib/db.ts"].some((pattern) => globMatch("src/app/globals.css", pattern)));
assert("modified locked migration fails", crypto.createHash("sha256").update("changed").digest("hex") !== cases.lockedHash);
assert("new valid migration passes", !/\b(?:DROP\s+TABLE|TRUNCATE)\b/i.test(cases.validMigration));
assert("enum-unsafe SQL fails", /COALESCE\s*\(\s*status\s*,\s*''/.test(cases.enumUnsafeSql));
assert("client service-role reference fails", /SUPABASE_SERVICE_ROLE_KEY/.test(cases.clientSecret));
assert("environment-reading helper fails", /readFileSync\s*\(\s*['\"]\.env/.test(cases.envReader));
assert("committed repair ZIP fails", /(?:repair|forensic|handoff).*\.(?:zip|7z|rar)$/i.test(cases.repairZip));
assert("missing test mapping fails", !cases.mappedProductionPaths.includes(cases.unmappedProductionPath));
assert("duplicate idempotency creation fails", (cases.duplicateIdempotency.match(/crypto\.randomUUID/g) ?? []).length > 1);
assert("manual apply mismatch fails", cases.migrationSql !== cases.manualApplySql);
assert("skipped E2E classification", cases.skippedEvidence.status === "SKIPPED");
assert("evidence report generation", cases.evidence.exitCode === 0 && cases.evidence.stdoutPath);
assert("context size enforcement", countWords(cases.context) <= 1500 && Buffer.byteLength(cases.context) <= 61440);
assert("stable context ordering", [...cases.paths].sort().join() === cases.paths.join());
assert("no secret content in output", !/eyJ[A-Za-z0-9_-]{10,}\./.test(cases.safeOutput));
assert("workflow has minimal permissions", /permissions:\s*\n\s+contents:\s*read/.test(workflow));
assert("workflow reads single Node version source", !/node-version:\s*\d/.test(workflow) && (workflow.match(/node-version-file:\s*\.node-version/g) ?? []).length >= 2);
assert("workflow uploads evidence", /actions\/upload-artifact@v4/.test(workflow) && /zerodata-harness-evidence/.test(workflow));
assert("workflow validates PR metadata", /harness:pr-metadata/.test(workflow) && /harness:scope/.test(fs.readFileSync(path.join(root, "scripts", "harness", "verify.mjs"), "utf8")));
assert("workflow contains no database writes", !/(?:supabase\s+db\s+(?:push|reset)|psql|02_APPLY\.sql)/i.test(workflow));
assert("workflow does not print secrets", !/(?:echo|print).*\$\{\{\s*secrets\./i.test(workflow));
assert("workflow labels absent E2E as skipped", /E2E acceptance: SKIPPED/.test(workflow));
assert("workflow has fewer than four npm installs", (workflow.match(/run:\s*npm ci/g) ?? []).length < 4);
assert("PR evidence avoids ignored local links", !/\(\[stdout\]\(|\(\[stderr\]\(/.test(reviewGenerator));
if (results.some((result) => !result.passed)) process.exit(1);
console.log(`Harness self-tests passed (${results.length} fixtures).`);
