"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { WalletCards } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { executeReceivableCommand,fetchReceivables,recoverReceivableCommands,type ReceivableCommandError } from "@/lib/receivables/client";
import type { ReceivableSummary } from "@/lib/receivables/types";
import { formatInr } from "@/lib/receivables/domain";
import { PageHeader } from "@/components/ui/PageHeader";import { Button } from "@/components/ui/Button";import { Chip } from "@/components/ui/Chip";
import { EmployeeReceivableActionModal,type EmployeeReceivableAction } from "@/components/receivables/EmployeeReceivableActionModal";

export default function PaymentFollowUpsPage(){
 const {isAdmin}=useAuth();const [rows,setRows]=useState<ReceivableSummary[]>([]),[message,setMessage]=useState(""),[selected,setSelected]=useState<{row:ReceivableSummary;action:EmployeeReceivableAction}|null>(null);
 const load=useCallback(async()=>{try{setRows((await fetchReceivables("?pageSize=50")).rows)}catch(error){setMessage(error instanceof Error?error.message:"Payment Follow-ups are unavailable.")}},[]);
 useEffect(()=>{void recoverReceivableCommands().then(result=>{if(result.confirmed)setMessage(`${result.confirmed} previously uncertain action was confirmed.`);void load()}).catch(()=>void load());const refresh=()=>{if(navigator.onLine)void load()};const visible=()=>{if(document.visibilityState==="visible")refresh()};const interval=window.setInterval(()=>{if(document.visibilityState==="visible")refresh()},60000);window.addEventListener("focus",refresh);window.addEventListener("online",refresh);document.addEventListener("visibilitychange",visible);return()=>{window.clearInterval(interval);window.removeEventListener("focus",refresh);window.removeEventListener("online",refresh);document.removeEventListener("visibilitychange",visible)}},[load]);
 const sorted=useMemo(()=>[...rows].sort((a,b)=>priority(a.alert_state)-priority(b.alert_state)||String(a.next_follow_up_date).localeCompare(String(b.next_follow_up_date))),[rows]);
 async function submit(payload:Record<string,unknown>){if(!selected)return;const commandPayload={receivable_id:selected.row.receivable_id,expected_version:selected.row.version,...payload,...(selected.action==="payment_report"?{payment_id:crypto.randomUUID()}:{})};try{await executeReceivableCommand({operation_id:crypto.randomUUID(),operation_type:selected.action,payload:commandPayload});setMessage(selected.action==="payment_report"?"Payment awaiting verification. Confirmed outstanding is unchanged.":"Collection action confirmed.");await load()}catch(cause){const error=cause as ReceivableCommandError;if(error.code==="RECEIVABLE_CONFLICT"||error.code==="RECEIVABLE_NOT_ASSIGNED")await load();throw error}}
 if(isAdmin)return <div className="app-page"><PageHeader title="Payment Follow-ups" description="Administrators use Payment Collections."/><a href="/admin/payments"><Button>Open Payment Collections</Button></a></div>;
 return <div className="app-page"><PageHeader eyebrow="Collections" icon={<WalletCards size={16}/>} title="Payment Follow-ups" description="Your assigned bills, ordered by urgency. Financial totals are server confirmed."/>{message&&<div className="alert-panel alert-panel--info" role="status">{message}</div>}<div className="grid gap-3">{sorted.map(row=><article key={row.receivable_id} className="surface-panel min-w-0 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-semibold">{row.distributor_name}</h2><Chip variant={row.alert_state.includes("overdue")?"danger":"warning"} size="sm">{row.alert_state.replaceAll("_"," ")}</Chip>{row.pending_payment_count>0&&<Chip variant="warning" size="sm">Payment awaiting verification</Chip>}</div><p className="mt-1 text-xs text-[var(--text-muted)]">Bill {row.bill_reference} · {row.contact_person}</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><Value label="Bill" value={formatInr(row.bill_amount)}/><Value label="Received" value={formatInr(row.confirmed_paid_amount)}/><Value label="Outstanding" value={formatInr(row.outstanding_amount)}/><Value label="Next action" value={row.promise_date??row.next_follow_up_date??"Awaiting schedule"}/></div></div>{row.lifecycle_status==="active"&&row.pending_payment_count===0&&<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setSelected({row,action:"contacted"})}>Contacted</Button><Button size="sm" variant="outline" onClick={()=>setSelected({row,action:"no_response"})}>No Response</Button><Button size="sm" variant="outline" onClick={()=>setSelected({row,action:"promise"})}>Promise to Pay</Button><Button size="sm" onClick={()=>setSelected({row,action:"payment_report"})}>Payment Reported</Button></div>}</div></article>)}{!rows.length&&!message&&<p className="text-sm text-[var(--text-muted)]">No assigned payment follow-ups.</p>}</div>{selected&&<EmployeeReceivableActionModal key={`${selected.row.receivable_id}:${selected.action}`} action={selected.action} open onClose={()=>setSelected(null)} onSubmit={submit}/>}</div>
}
function Value({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-semibold uppercase text-[var(--text-muted)]">{label}</p><p className="mt-1 break-words text-sm font-semibold tabular-nums">{value}</p></div>}
function priority(state:string){const index=["promise_overdue","followup_overdue","promise_due_today","followup_due_today","upcoming","payment_verification_pending","disputed","none"].indexOf(state);return index<0?99:index}
