import fs from "fs";import path from "path";const read=(p:string)=>fs.readFileSync(path.join(process.cwd(),p),"utf8");
describe("receivables server and recovery boundaries",()=>{
 test("readiness is server-only and defaults closed",()=>{const server=read("src/lib/receivables/server.ts");expect(server).toContain('process.env.RECEIVABLES_V1_READY === "true"');expect(server).not.toContain("NEXT_PUBLIC_RECEIVABLES")});
 test("server derives bearer identity and active capability",()=>{const server=read("src/lib/receivables/server.ts");expect(server).toContain("auth.getUser(token)");expect(server).toContain('from("users")');expect(server).toContain('capability_code==="admin"')});
 test("outbox is narrow, owner-keyed and replays exact commands",()=>{const client=read("src/lib/receivables/client.ts");expect(client).toContain("zerodata:receivables-outbox:${userId}");expect(client).toContain("item.command");expect(client).not.toContain("processSyncQueue");expect(client).not.toMatch(/\.from\(["']receivable/)});
 test("mutation routes ignore client actor and pass authenticated actor",()=>{const route=read("src/app/api/receivables/commands/route.ts");expect(route).toContain("p_actor_id:context.userId");expect(route).not.toContain("body.actor_id")});
 test("deterministic DB conflicts are terminal HTTP results",()=>{const route=read("src/app/api/receivables/commands/route.ts"),client=read("src/lib/receivables/client.ts");for(const code of ["RECEIVABLE_DUPLICATE","PAYMENT_DUPLICATE","RECEIVABLE_ALREADY_PAID","PAYMENT_VERIFICATION_PENDING","INVALID_RECEIVABLE_STATE"])expect(route).toContain(code);expect(client).toContain("status>=500")});
 test("employee pagination is server ordered and reaches beyond fifty",()=>{const route=read("src/app/api/receivables/route.ts"),page=read("src/app/payments/page.tsx");expect(route).toContain('order("collection_priority"');expect(route).toContain('order("collection_sort_date"');expect(page).toContain("pageSize=25");expect(page).toContain("Load more");expect(page).toContain("Showing {rows.length} of {total}")});
 test("employee UI mirrors terminal DB states without exposing action controls",()=>{const page=read("src/app/payments/page.tsx");expect(page).toContain('row.payment_state==="Paid"');expect(page).toContain('row.lifecycle_status==="cancelled"');expect(page).toContain('row.lifecycle_status==="disputed"');expect(page).toContain("row.pending_payment_count>0");expect(page).toContain("reason?<p")});
 test("confirmation compares a rebuilt complete preview binding",()=>{const route=read("src/app/api/receivables/import/route.ts"),binding=read("src/lib/receivables/importBinding.ts");expect(route).toContain("parsed.data.preview_hash!==preview.preview_hash");for(const field of ["row_number","receivable_id","bill_reference","distributor_name","distributor_code","contact_person","contact_phone","bill_amount","bill_due_date","next_follow_up_date","assigned_to","notes"])expect(binding).toContain(field)});
});
