const getServerBackendEnvironment = jest.fn();
jest.mock("@/lib/serverBackendIdentity", () => ({ getServerBackendEnvironment }));

import fs from "fs"; import path from "path"; import { GET } from "@/app/api/receivables/route";
const read=(p:string)=>fs.readFileSync(path.join(process.cwd(),p),"utf8"); const sql=read("supabase/migrations/033_receivables_v1.sql"); const completion=read("supabase/migrations/034_receivables_production_completion.sql"); const linearImport=read("supabase/migrations/035_receivables_import_linearization.sql");
describe("receivables database financial/concurrency contract",()=>{
 test("confirmed-only numeric read model derives payment state and no negative balance",()=>{expect(sql).toContain("filter(where verification_status='confirmed')");expect(sql).toMatch(/bill_amount-coalesce\(m\.confirmed_paid_amount,0\)/);expect(sql).toContain("payment_state");expect(sql).toContain("v_payment.amount>v_r.bill_amount-v_paid")});
 test("all existing-record commands lock and version-check",()=>{expect(sql).toMatch(/for update;[\s\S]*RECEIVABLE_CONFLICT/);expect(sql).toContain("version=version+1");expect(sql).toContain("pg_advisory_xact_lock");});
 test("idempotency binds operation, actor, type and request hash",()=>{expect(sql).toMatch(/v_receipt\.actor_id<>p_actor_id[\s\S]*v_receipt\.operation_type<>p_operation_type[\s\S]*v_receipt\.request_hash<>p_request_hash/);expect(sql).toContain("RECEIVABLE_OPERATION_MISMATCH")});
 test("reports do not reduce balance and reversal preserves history",()=>{expect(sql).toContain("verification_status='reported'");expect(sql).toContain("verification_status='reversed'");expect(sql).not.toMatch(/delete\s+from\s+public\.receivable/i)});
 test("latest operational event supersedes stale promise",()=>{expect(sql).toMatch(/distinct on\(receivable_id\)[\s\S]*event_type in \('followup_contacted','followup_no_response','promise_to_pay'/)});
 test("service-only functions and browser read-only grants",()=>{expect(sql).toMatch(/revoke all on function public\.execute_receivable_command_v1.*authenticated/);expect(sql).toMatch(/grant execute on function public\.execute_receivable_command_v1.*service_role/);expect(sql).not.toMatch(/grant\s+(insert|update|delete).*authenticated/i)});
 test("import is bounded, transactional, active-user resolved and retry-stable",()=>{expect(sql).toContain("jsonb_array_length(p_rows)>5000");expect(sql).toContain("IMPORT_EMPLOYEE_CHANGED");expect(sql).toContain("IMPORT_REFRESH_REQUIRED");expect(sql).toContain("receivable_import_batches")});
 test("5,000-row import uses indexed transaction-local staging instead of growing JSONB concatenation",()=>{expect(linearImport).toContain("create temporary table if not exists receivables_import_stage_v1");expect(linearImport).toContain("primary key(operation_id,business_key)");expect(linearImport).not.toContain("v_accepted:=v_accepted||");expect(linearImport).not.toContain("v_seen:=v_seen||")});
 test("paid, pending verification, lifecycle, and duplicate identities are typed authority checks",()=>{for(const code of ["RECEIVABLE_ALREADY_PAID","PAYMENT_VERIFICATION_PENDING","INVALID_RECEIVABLE_STATE","RECEIVABLE_DUPLICATE","PAYMENT_DUPLICATE"])expect(sql).toContain(code);expect(sql).toContain("v_r.bill_amount-v_paid<=0");expect(sql).toContain("v_pending>0")});
 test("operational assignment excludes Admin accounts at database authority",()=>{expect(completion).toContain("receivables_operational_assignee_guard_v1");expect(completion).toContain("capability_code = 'admin'");expect(completion).toContain("errcode = 'ZD001'");expect(completion).not.toMatch(/delete\s+from/i)});
});

describe("receivables request authentication",()=>{
 const originalEnvironment={...process.env}, originalFetch=global.fetch, userId="20000000-0000-4000-a000-000000000001", serviceKey=["server","fixture","key"].join("-"); let role:"employee"|"admin"="employee", requests:Array<{url:string;authorization:string|null}>=[];
 const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","content-range":"*/0"}});
 beforeEach(()=>{process.env={...originalEnvironment,RECEIVABLES_V1_READY:"true",SUPABASE_SERVICE_ROLE_KEY:serviceKey};role="employee";requests=[];getServerBackendEnvironment.mockReturnValue({status:"configured",deployment:"production",reason:"AUTHORIZED_PRODUCTION",url:"https://authorized.example",anonKey:"public-fixture-key"});global.fetch=jest.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const request=new Request(input,init),authorization=request.headers.get("authorization"),url=request.url;requests.push({url,authorization});if(url.includes("/auth/v1/user"))return authorization==="Bearer invalid-token"?json({message:"invalid"},401):json({id:userId,aud:"authenticated",role:"authenticated",email:"employee@example.test"});if(url.includes("/rest/v1/users"))return json({user_id:userId,is_active:true});if(url.includes("/rest/v1/user_capabilities"))return json(role==="admin"?[{capability_code:"admin"}]:[]);if(url.includes("/rest/v1/receivables_financial_read_v1"))return json([]);if(url.includes("/rest/v1/receivables_financial_read_v2"))return json([]);return json({message:"unexpected request"},500);}) as typeof fetch;});
 afterAll(()=>{process.env=originalEnvironment;global.fetch=originalFetch;});
 test("forwards the employee bearer token to the RLS financial read",async()=>{const response=await GET(new Request("http://localhost/api/receivables",{headers:{authorization:"Bearer employee-token"}}));expect(response.status).toBe(200);const read=requests.find(({url})=>url.includes("receivables_financial_read_v1"));expect(read?.authorization).toBe("Bearer employee-token");expect(requests.some(({url})=>url.includes("receivables_financial_read_v2"))).toBe(false);});
 test("keeps administrator financial reads on the service client",async()=>{role="admin";const response=await GET(new Request("http://localhost/api/receivables",{headers:{authorization:"Bearer admin-token"}}));expect(response.status).toBe(200);const read=requests.find(({url})=>url.includes("receivables_financial_read_v2"));expect(read?.authorization).toBe(`Bearer ${serviceKey}`);expect(requests.some(({url})=>url.includes("receivables_financial_read_v1"))).toBe(false);});
 test.each([["missing",undefined,0],["invalid","Bearer invalid-token",1]] as const)("rejects %s authentication before financial reads",async(_label,authorization,expectedRequests)=>{const response=await GET(new Request("http://localhost/api/receivables",authorization?{headers:{authorization}}:undefined));expect(response.status).toBe(401);expect(requests).toHaveLength(expectedRequests);expect(requests.some(({url})=>url.includes("receivables_financial_read"))).toBe(false);});
 test("makes no backend request when the environment is unavailable",async()=>{getServerBackendEnvironment.mockReturnValue({status:"unavailable",deployment:"preview",reason:"PREVIEW_BACKEND_DISABLED"});const response=await GET(new Request("http://localhost/api/receivables",{headers:{authorization:"Bearer employee-token"}}));expect(response.status).toBe(503);expect(await response.json()).toEqual({error:"CRM_UNAVAILABLE"});expect(requests).toHaveLength(0);});
});
