"use client";
import { useCallback,useEffect,useState } from "react"; import Link from "next/link"; import { IndianRupee,AlertTriangle } from "lucide-react"; import { supabase } from "@/lib/supabaseClient"; import { formatInr } from "@/lib/receivables/domain"; import { Chip } from "@/components/ui/Chip"; import { Button } from "@/components/ui/Button";
import { getCurrentISTDate,getISTBusinessDayBounds } from "@/lib/dateTime";
interface Row{receivable_id:string;distributor_name:string;bill_reference:string;outstanding_amount:string;alert_state:string}
export default function PaymentCollectionsPriorityPanel(){const [state,setState]=useState<{enabled:boolean;admin?:boolean;verificationPending?:number;urgentCount:number;outstandingAmount:string;rows:Row[]}|null>(null);
 const refresh=useCallback(async()=>{if(!navigator.onLine)return;const {data}=await supabase.auth.getSession();if(!data.session?.access_token)return;const response=await fetch("/api/my-day/receivables",{headers:{Authorization:`Bearer ${data.session.access_token}`},cache:"no-store"});if(response.ok)setState(await response.json());},[]);
 useEffect(()=>{void refresh();const visible=()=>{if(document.visibilityState==="visible")void refresh()};const rollover=getISTBusinessDayBounds(getCurrentISTDate());const timer=window.setTimeout(()=>void refresh(),Math.max(1000,new Date(rollover.endsAt).getTime()-Date.now()+250));window.addEventListener("online",refresh);window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",visible);return()=>{window.removeEventListener("online",refresh);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",visible);window.clearTimeout(timer)}},[refresh]);
 if(!state?.enabled)return null;if(state.admin)return state.verificationPending?<section className="mb-5 rounded-[var(--radius-xl)] border-2 border-[var(--status-warning)]/40 bg-[var(--status-warning-soft)] p-5 shadow-[var(--shadow-raised)]" aria-labelledby="admin-payment-priority"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-[var(--radius-lg)] bg-[var(--surface-primary)] text-[var(--status-warning)]"><AlertTriangle size={20}/></span><div><p className="section-kicker">Admin priority</p><h2 id="admin-payment-priority" className="section-title">Payment reports awaiting verification</h2><p className="mt-1 text-sm font-semibold">{state.verificationPending} report{state.verificationPending===1?"":"s"} require authoritative review</p></div></div><Link href="/admin/payments"><Button size="sm">Review payment reports</Button></Link></div></section>:null;if(!state.rows.length)return null;const label=(s:string)=>s.replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());
 return <section className="mb-5 overflow-hidden rounded-[var(--radius-xl)] border-2 border-[var(--status-danger)]/35 bg-[var(--status-danger-soft)] shadow-[var(--shadow-raised)]" aria-labelledby="receivables-priority-title">
  <div className="flex flex-col gap-3 border-b border-[var(--status-danger)]/20 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-[var(--radius-lg)] bg-[var(--surface-primary)] text-[var(--status-danger)]"><IndianRupee size={21}/></span><div><p className="section-kicker">High priority</p><h2 id="receivables-priority-title" className="section-title">Payment Collections</h2><p className="mt-1 text-sm font-semibold">{state.urgentCount} urgent follow-up{state.urgentCount===1?"":"s"} · {formatInr(state.outstandingAmount)} outstanding</p></div></div><Link href="/payments"><Button size="sm">View all payment follow-ups</Button></Link></div>
  <div className="grid gap-2 p-4 sm:grid-cols-2 lg:grid-cols-3">{state.rows.slice(0,5).map(row=><article key={row.receivable_id} className="min-w-0 rounded-[var(--radius-lg)] border border-[var(--border-default)] bg-[var(--surface-primary)] p-4"><div className="flex items-start gap-2"><AlertTriangle size={16} className="mt-0.5 shrink-0 text-[var(--status-danger)]"/><div className="min-w-0"><p className="truncate text-sm font-semibold">{row.distributor_name}</p><p className="mt-1 text-lg font-semibold tabular-nums">{formatInr(row.outstanding_amount)}</p><Chip variant="danger" size="sm">{label(row.alert_state)}</Chip></div></div></article>)}</div>
 </section>}
