import {buildDistributorImportPreview} from "@/lib/distributors/importServer";
import type {DistributorImportRow} from "@/lib/distributors/import";

jest.mock("server-only",()=>({}),{virtual:true});

const employee={user_id:"20000000-0000-4000-a000-000000000001",name:"Employee",email:"employee@example.com"};
const base:DistributorImportRow={rowNumber:2,distributorName:"Alpha",assignedEmployeeEmail:"employee@example.com",installationStatus:"done",installationDate:"2026-08-13",trainingStatus:"done",trainingDate:"2026-08-13",activityStatus:"active",billingStatus:"billed",billDate:"2026-08-13",billReference:"B-1",renewalDate:"2027-08-13",distributorReference:"ALPHA-1"};
function service(existing:Record<string,unknown>[]=[],users=[employee]){return {from(table:string){const result=table==="users"?{data:users}:table==="user_capabilities"?{data:[]}:{data:existing,error:null};const builder={select(){return builder},eq(){return Promise.resolve(result)},in(){return Promise.resolve(result)},then(resolve:(value:typeof result)=>unknown){return Promise.resolve(result).then(resolve)}};return builder}} as never}

describe("Distributor import commit authority",()=>{
  test("re-derives NEW identity, assignee and stable ID instead of trusting browser classifications",async()=>{const tampered={...base,classification:"EXACT_DUPLICATE",identity_key:"code:attacker",assigned_to:"attacker",distributor_id:"attacker",expected_version:999} as DistributorImportRow;const preview=await buildDistributorImportPreview(service(),"30000000-0000-4000-a000-000000000001",[tampered]);expect(preview.rows[0]).toMatchObject({classification:"NEW",payload:{identity_key:"code:alpha-1",assigned_to:employee.user_id}});expect((preview.rows[0] as {payload:Record<string,unknown>}).payload.distributor_id).not.toBe("attacker")});
  test("reclassifies authoritative UPDATE target and version",async()=>{const current={distributor_id:"40000000-0000-4000-a000-000000000001",identity_key:"code:alpha-1",distributor_name:"Alpha",distributor_reference:"ALPHA-1",assigned_to:employee.user_id,installation_status:"pending",installation_completed_at:null,training_status:"pending",training_completed_at:null,activity_status:"not_applicable",billing_status:"not_billed",billed_at:null,bill_reference:"",renewal_date:null,version:7};const preview=await buildDistributorImportPreview(service([current]),"30000000-0000-4000-a000-000000000001",[{...base,distributor_id:"attacker",expected_version:1} as DistributorImportRow]);expect(preview.rows[0]).toMatchObject({classification:"UPDATE",payload:{distributor_id:current.distributor_id,expected_version:7}})});
  test("binds employee changes, same-file duplicates, and database changes into a new authoritative result",async()=>{const first=await buildDistributorImportPreview(service(),"30000000-0000-4000-a000-000000000001",[base]);const reassigned=await buildDistributorImportPreview(service([], [{...employee,user_id:"20000000-0000-4000-a000-000000000002"}]),"30000000-0000-4000-a000-000000000001",[base]);expect(reassigned.preview_hash).not.toBe(first.preview_hash);const duplicate=await buildDistributorImportPreview(service(),"30000000-0000-4000-a000-000000000001",[base,{...base,rowNumber:3}]);expect(duplicate.rows[1].classification).toBe("AMBIGUOUS");const appeared=await buildDistributorImportPreview(service([{distributor_id:"40000000-0000-4000-a000-000000000009",identity_key:"code:alpha-1",distributor_name:"Alpha",distributor_reference:"ALPHA-1",assigned_to:employee.user_id,installation_status:"pending",installation_completed_at:null,training_status:"pending",training_completed_at:null,activity_status:"not_applicable",billing_status:"not_billed",billed_at:null,bill_reference:"",renewal_date:null,version:1}]),"30000000-0000-4000-a000-000000000001",[base]);expect(appeared.preview_hash).not.toBe(first.preview_hash);expect(appeared.rows[0].classification).toBe("UPDATE")});
});
