import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { Command, MemorySaver } from "@langchain/langgraph";
import { SqliteSaver } from "@langchain/langgraph-checkpoint-sqlite";
import { buildGraph } from "../src/graph.js";
import { inspectRepo } from "../src/git.js";
import { parseResumeEnvelope, pendingHumanInterrupt } from "../src/resume.js";

function git(cwd:string,...args:string[]){return execFileSync("git",["-C",cwd,...args],{encoding:"utf8"}).trim();}
function fixture(release=false,secondImplementation=false) {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"crm-graph-life-"));git(root,"init","-b","main");git(root,"config","user.email","graph@test.invalid");git(root,"config","user.name","Graph Test");
  for(const dir of [".crm-engineering/tasks",".crm-engineering/knowledge",".crm-engineering/policy"])fs.mkdirSync(path.join(root,dir),{recursive:true});
  fs.writeFileSync(path.join(root,".crm-engineering/manifest.json"),'{}');
  fs.writeFileSync(path.join(root,".crm-engineering/knowledge/authority-registry.json"),'{"facts":[]}');
  fs.writeFileSync(path.join(root,".crm-engineering/knowledge/capability-registry.json"),'{"capabilities":[]}');
  fs.writeFileSync(path.join(root,".crm-engineering/knowledge/lessons-registry.json"),'{"lessons":[]}');
  fs.writeFileSync(path.join(root,".crm-engineering/policy/applied-migrations.json"),'{"immutableThrough":44}');
  const acceptance:any[]=[
    {id:"A",description:"implement",stage:"IMPLEMENTATION",status:"PENDING",required:true,evidenceIds:[]},
  ];
  if(secondImplementation)acceptance.push({id:"A2",description:"implement second",stage:"IMPLEMENTATION",status:"PENDING",required:true,evidenceIds:[]});
  acceptance.push({id:"V",description:"verify",stage:"VERIFICATION",status:"PENDING",required:true,evidenceIds:[]});
  if(release)acceptance.push({id:"R",description:"release",stage:"RELEASE",status:"PENDING",required:true,evidenceIds:[]});
  const task:any={schemaVersion:2,graphSchemaVersion:1,flowVersion:"1.1.0",taskId:"T",objective:"lifecycle",risk:"R0",domains:["engineering-graph"],repository:{canonicalRoot:root,worktreePath:root,branch:"main",expectedBaseRef:"HEAD",expectedBaseSha:null,observedHeadSha:null,dirtyBaselineHash:null},phase:"IMPLEMENTATION",allowedPaths:[".crm-engineering/**"],protectedDomains:[],productionDataMutation:false,schemaChange:false,humanGate:release?{kind:"OWNER_PRODUCTION_GATE",status:"PENDING",reason:"manual"}:null,acceptance,blocker:null};
  const taskPath=path.join(root,".crm-engineering/tasks/T.json");fs.writeFileSync(taskPath,JSON.stringify(task,null,2));git(root,"add",".");git(root,"commit","-m","fixture");
  task.repository.expectedBaseSha=git(root,"rev-parse","HEAD");task.repository.observedHeadSha=task.repository.expectedBaseSha;task.repository.dirtyBaselineHash=inspectRepo(root).dirtyHash;fs.writeFileSync(taskPath,JSON.stringify(task,null,2));
  return {root,task};
}
function initial(root:string,task:any):any{return {graphSchemaVersion:1,flowVersion:"1.1.0",taskId:"T",objective:"lifecycle",mode:"enforce",canonicalRoot:root,graphRoot:root,worktreePath:root,branch:"main",expectedBaseRef:"HEAD",expectedBaseSha:task.repository.expectedBaseSha,observedHeadSha:task.repository.observedHeadSha,dirtyBaselineHash:task.repository.dirtyBaselineHash,risk:"R0",domains:["engineering-graph"],allowedPaths:[".crm-engineering/**"],protectedDomains:[],phase:"IMPLEMENTATION",acceptance:task.acceptance,blocker:null,currentNode:"START",nextLegalAction:"",contextPacket:"",repoHealthy:false,implementationComplete:false,broadVerificationAllowed:false,canEnd:false,beforeDiffHash:null,beforeChangedPaths:[],afterDiffHash:null,beforePassCount:0,afterPassCount:0,stallCount:0,workerIntent:"IMPLEMENT",focusedAcceptanceId:null,workerRetryMode:"INITIAL",workerFailureCount:0,workerErrorHistory:[],workerStrategyGuidance:null,codexThreadId:null,codexLastMessage:"",codexResultValid:false,lastWorkerError:null,findings:[]};}
class Worker { intents:string[]=[]; calls=0; close(){}; async run(task:any,_context:string,intent:string,acceptance:any){this.calls++;this.intents.push(intent);return{threadId:"thread",raw:"ok",result:{taskId:task.taskId,acceptanceUpdates:[{id:acceptance.id,status:"PASS",evidenceIds:[`test:${acceptance.id}`]}],changedPaths:[],externalBlocker:null,summary:"ok"}};}}

test("implementation PASS advances and verification worker is invoked",async()=>{const f=fixture();const w=new Worker();const graph=buildGraph(new MemorySaver(),w as any);const result:any=await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.deepEqual(w.intents,["IMPLEMENT","VERIFY"]);assert.equal(result.phase,"COMPLETE");});
test("full implementation plus verification reaches legal END",async()=>{const f=fixture();const graph=buildGraph(new MemorySaver(),new Worker() as any);const result:any=await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.equal(result.canEnd,true);assert.equal(result.nextLegalAction,"END");});
test("broad verification is not invoked before implementation",async()=>{const f=fixture();const w=new Worker();const graph=buildGraph(new MemorySaver(),w as any);await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.equal(w.intents[0],"IMPLEMENT");assert.equal(w.intents[1],"VERIFY");});

test("every required implementation acceptance executes before required verification",async()=>{const f=fixture(false,true);const calls:{intent:string;id:string}[]=[];const worker={close(){},async run(task:any,_context:string,intent:string,acceptance:any){calls.push({intent,id:acceptance.id});return{threadId:"thread",raw:"ok",result:{taskId:task.taskId,acceptanceUpdates:[{id:acceptance.id,status:"PASS",evidenceIds:[`test:${acceptance.id}`]}],changedPaths:[],externalBlocker:null,summary:"ok"}};}};const graph=buildGraph(new MemorySaver(),worker as any);await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.deepEqual(calls,[{intent:"IMPLEMENT",id:"A"},{intent:"IMPLEMENT",id:"A2"},{intent:"VERIFY",id:"V"}]);});

test("runtime failure is checkpointed and follows focused retry, strategy change, escalation",async()=>{const f=fixture();const saver=new MemorySaver();const retryModes:string[]=[];const worker={calls:0,close(){},async run(_t:any,_c:any,_i:any,_a:any,_thread:any,runtime:any){this.calls++;retryModes.push(runtime.retryMode);throw Object.assign(new Error("transport"),{code:"CODEX_APP_SERVER_EXIT",stderrTail:"tail"});}};const graph=buildGraph(saver,worker as any);const result:any=await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.equal(worker.calls,3);assert.deepEqual(retryModes,["INITIAL","FOCUSED_RETRY","STRATEGY_CHANGE"]);assert.ok(result.__interrupt__);const tuple:any=await saver.getTuple({configurable:{thread_id:"T"}});const saved=tuple.checkpoint.channel_values;assert.equal(saved.lastWorkerError.code,"CODEX_APP_SERVER_EXIT");assert.equal(saved.lastWorkerError.attempt,3);assert.equal(saved.workerRetryMode,"ESCALATE");assert.deepEqual(saved.workerErrorHistory.map((error:any)=>error.attempt),[1,2,3]);assert.equal(saved.workerErrorHistory[2].stderrTail,"tail");});

test("malformed external blocker is checkpointed as a worker error instead of crashing state validation",async()=>{const f=fixture();const saver=new MemorySaver();const worker={close(){},async run(task:any,_c:any,_i:any,acceptance:any){return{threadId:"thread",raw:"malformed",result:{taskId:task.taskId,acceptanceUpdates:[{id:acceptance.id,status:"PENDING",evidenceIds:[]}],changedPaths:[],externalBlocker:{},summary:"partial"}};}};const graph=buildGraph(saver,worker as any);const result:any=await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.ok(result.__interrupt__);const tuple:any=await saver.getTuple({configurable:{thread_id:"T"}});const saved=tuple.checkpoint.channel_values;assert.equal(saved.lastWorkerError.code,"CODEX_WORKER_RUNTIME_ERROR");assert.match(saved.lastWorkerError.message,/MALFORMED_EXTERNAL_BLOCKER/);assert.equal(saved.blocker,null);});

test("release acceptance creates durable human interrupt checkpoint",async()=>{const f=fixture(true);const saver=new MemorySaver();const graph=buildGraph(saver,new Worker() as any);const result:any=await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.ok(result.__interrupt__);const tuple=await saver.getTuple({configurable:{thread_id:"T"}});assert.ok(tuple);});

test("resume on same thread cannot pass release without durable evidence",async()=>{const f=fixture(true);const saver=new MemorySaver();const graph=buildGraph(saver,new Worker() as any);const config={configurable:{thread_id:"T"},recursionLimit:64};await graph.invoke(initial(f.root,f.task),config);const resumed:any=await graph.invoke(new Command({resume:{approved:true}}),config);assert.ok(resumed.__interrupt__);const saved=JSON.parse(fs.readFileSync(path.join(f.root,".crm-engineering/tasks/T.json"),"utf8"));assert.equal(saved.acceptance.find((x:any)=>x.id==="R").status,"PENDING");});

test("SQLite interrupt resumes through structured input on the same durable thread",async()=>{const f=fixture(true);const sqlite=path.join(f.root,".crm-engineering/runtime/a05.sqlite");fs.mkdirSync(path.dirname(sqlite),{recursive:true});const config={configurable:{thread_id:"T"},recursionLimit:64};const firstGraph=buildGraph(SqliteSaver.fromConnString(sqlite),new Worker() as any);const interrupted:any=await firstGraph.invoke(initial(f.root,f.task),config);assert.ok(interrupted.__interrupt__);const restartedGraph=buildGraph(SqliteSaver.fromConnString(sqlite),new Worker() as any);const pending=await pendingHumanInterrupt(restartedGraph,config);assert.equal(pending.type,"OWNER_PRODUCTION_GATE");const payload=parseResumeEnvelope({taskId:"T",threadId:"T",type:"OWNER_PRODUCTION_GATE",input:{verified:true,evidenceIds:["test:owner-postcheck"]}},"T",pending.type);const resumed:any=await restartedGraph.invoke(new Command({resume:payload}),config);assert.equal(resumed.canEnd,true);const saved=JSON.parse(fs.readFileSync(path.join(f.root,".crm-engineering/tasks/T.json"),"utf8"));assert.equal(saved.acceptance.find((item:any)=>item.id==="R").status,"PASS");});

test("SQLite stalled-agent interrupt resumes with structured strategy guidance",async()=>{const f=fixture();const sqlite=path.join(f.root,".crm-engineering/runtime/a05-stall.sqlite");fs.mkdirSync(path.dirname(sqlite),{recursive:true});const config={configurable:{thread_id:"T"},recursionLimit:64};const failing={close(){},async run(){throw Object.assign(new Error("transport"),{code:"CODEX_APP_SERVER_EXIT"});}};const firstGraph=buildGraph(SqliteSaver.fromConnString(sqlite),failing as any);const interrupted:any=await firstGraph.invoke(initial(f.root,f.task),config);assert.ok(interrupted.__interrupt__);const runtimes:any[]=[];const recovering={close(){},async run(task:any,_context:string,_intent:string,acceptance:any,_thread:any,runtime:any){runtimes.push(runtime);return{threadId:"saved-codex-thread",raw:"ok",result:{taskId:task.taskId,acceptanceUpdates:[{id:acceptance.id,status:"PASS",evidenceIds:[`test:${acceptance.id}`]}],changedPaths:[],externalBlocker:null,summary:"recovered"}};}};const restartedGraph=buildGraph(SqliteSaver.fromConnString(sqlite),recovering as any);const pending=await pendingHumanInterrupt(restartedGraph,config);assert.equal(pending.type,"AGENT_STALL");const payload=parseResumeEnvelope({taskId:"T",threadId:"T",type:"AGENT_STALL",input:{guidance:"retry with a fresh transport",strategy:"restart transport before the turn"}},"T",pending.type);const resumed:any=await restartedGraph.invoke(new Command({resume:payload}),config);assert.equal(resumed.canEnd,true);assert.equal(runtimes[0].retryMode,"STRATEGY_CHANGE");assert.match(runtimes[0].strategyGuidance,/fresh transport/);});

test("structured resume rejects cross-thread and wrong-interrupt input",()=>{assert.throws(()=>parseResumeEnvelope({taskId:"OTHER",threadId:"OTHER",type:"AGENT_STALL",input:{guidance:"retry"}},"T","AGENT_STALL"),/THREAD_MISMATCH/);assert.throws(()=>parseResumeEnvelope({taskId:"T",threadId:"T",type:"AGENT_STALL",input:{guidance:"retry"}},"T","OWNER_PRODUCTION_GATE"),/TYPE_MISMATCH/);});

test("scope violation terminates safely",async()=>{const f=fixture();const worker={close(){},async run(task:any,_c:string,_i:string,a:any){fs.mkdirSync(path.join(f.root,"src"));fs.writeFileSync(path.join(f.root,"src/bad.ts"),"bad");return{threadId:"t",raw:"ok",result:{taskId:task.taskId,acceptanceUpdates:[{id:a.id,status:"PASS",evidenceIds:["test"]}],changedPaths:["src/bad.ts"],externalBlocker:null,summary:""}};}};const graph=buildGraph(new MemorySaver(),worker as any);const result:any=await graph.invoke(initial(f.root,f.task),{configurable:{thread_id:"T"},recursionLimit:64});assert.equal(result.blocker.type,"SAFETY_VIOLATION");});
