"use client";

import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AnalyticsBoundary, AnalyticsEmptyState, AnalyticsPanel } from "@/components/analytics/AnalyticsPanel";
import { ChartContainer, ChartTooltipContent } from "@/components/analytics/Chart";
import { FieldMix } from "@/components/analytics/CompositionCharts";
import { buildVisitAnalytics, VISIT_OUTCOMES, type VisitAnalyticsSource } from "@/lib/analytics/viewModels";
import type { VisitSummaryReport } from "@/lib/fieldVisits/range";
import { adminVisitOutcomeLabel } from "@/lib/fieldVisits/query";

export default function VisitSummaryCharts({ report, scope, matchedTotal, visits, page, onOutcome, onRepresentative }: {
  report: VisitSummaryReport; scope: string; matchedTotal: number; visits: VisitAnalyticsSource[]; page: number;
  onOutcome: (key: string) => void; onRepresentative: (id: string) => void;
}) {
  const outcomes = Object.entries(report.outcomes).map(([key, value]) => ({ key, label: adminVisitOutcomeLabel(key), value, color: VISIT_OUTCOMES.find((item) => item.key === key)?.color ?? "var(--viz-muted)" }));
  if (report.unknown_outcome_count) outcomes.push({ key: "unknown", label: "Unknown / legacy outcome", value: report.unknown_outcome_count, color: "var(--viz-muted)" });
  const activity = report.activity.map((row) => ({ ...row, label: row.start_date === row.end_date ? row.start_date : `${row.start_date} – ${row.end_date}` }));
  const model = buildVisitAnalytics(visits);
  return <AnalyticsBoundary><section aria-label="Full-range Visit activity" className="space-y-3">
    <header><h2 className="section-title">Visits in the confirmed scope</h2><p className="text-sm"><strong>{report.filtered_total.toLocaleString("en-IN")}</strong> retained Visit records · {scope}</p><p className="text-xs text-[var(--text-secondary)]">Updated {new Date(report.generated_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST · canonical Visit dates</p></header>
    {matchedTotal !== report.filtered_total && <p role="status" className="alert-panel alert-panel--warning">Register and summary were read at different times: {matchedTotal} register records and {report.filtered_total} summary records. Refresh to reconcile.</p>}
    <div className="analytics-shell">
      <AnalyticsPanel title="Outcome composition" description="Complete confirmed scope · Select an outcome to filter all results." labelledBy="visits-outcome-donut">
        {report.filtered_total ? <div className="relative h-[280px]"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 320, height: 280 }}><PieChart accessibilityLayer><Pie data={outcomes.filter((row) => row.value > 0)} dataKey="value" nameKey="label" innerRadius="62%" outerRadius="88%" stroke="var(--surface-primary)" isAnimationActive={false}>{outcomes.filter((row) => row.value > 0).map((row) => <Cell key={row.key} fill={row.color} />)}</Pie><Tooltip formatter={(value, _name, item) => [`${value} of ${report.filtered_total}`, item.payload.label]} contentStyle={{ backgroundColor: "var(--surface-elevated)", color: "var(--text-primary)", border: "1px solid var(--border-default)" }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><strong className="block text-3xl tabular-nums">{report.filtered_total}</strong><span className="text-xs">Matching visits</span></div></div></div> : <AnalyticsEmptyState title="No visits match this scope" description="Adjust the filters to inspect another scope." />}
        <ul className="space-y-1 text-sm" aria-label="Visit outcome values">{outcomes.map((row) => <li key={row.key}>{row.key === "unknown" ? <div className="flex justify-between gap-3 py-2"><span>{row.label}</span><span>{row.value} of {report.filtered_total}</span></div> : <button type="button" className="flex min-h-11 w-full items-center justify-between gap-3 text-left underline underline-offset-4" aria-label={`Filter outcome: ${row.label}`} onClick={() => onOutcome(row.key)}><span><span className="mr-2 inline-block size-2 rounded-full" style={{ background: row.color }} />{row.label}</span><span className="shrink-0 tabular-nums">{row.value} of {report.filtered_total}</span></button>}</li>)}</ul>
      </AnalyticsPanel>
      <AnalyticsPanel title="Visit activity flow" description={report.bucket_days === 1 ? "Daily confirmed visits" : `Confirmed visits in ${report.bucket_days}-day intervals`} labelledBy="visits-activity-flow">
        {report.filtered_total ? <ChartContainer config={{ count: { label: "Retained visits", color: "var(--viz-primary)" } }} className="h-[280px] w-full" initialDimension={{ width: 520, height: 280 }}><AreaChart data={activity} accessibilityLayer margin={{ left: 0, right: 16, top: 16, bottom: 8 }}><CartesianGrid vertical={false} stroke="var(--viz-grid)" /><XAxis dataKey="label" tickFormatter={(value: string) => value.length > 10 ? `${value.slice(5, 10)}..${value.slice(-5)}` : value.slice(5, 10)} minTickGap={24} tickLine={false} axisLine={false} /><YAxis allowDecimals={false} domain={[0, "auto"]} width={40} tickLine={false} axisLine={false} /><Tooltip filterNull={false} content={<ChartTooltipContent />} /><Area dataKey="count" type="linear" connectNulls={false} stroke="var(--viz-primary)" fill="var(--viz-primary)" fillOpacity={0.18} strokeWidth={2} dot={{ r: 3 }} isAnimationActive={false} /></AreaChart></ChartContainer> : <AnalyticsEmptyState title="No visits match this scope" description="The requested dates are retained below with zero counts." />}
        <details className="workspace-disclosure"><summary>Exact activity chart data</summary><table className="w-full text-sm"><caption>Retained Visit records · IST</caption><thead><tr><th scope="col">Date or interval</th><th scope="col">Retained visits</th></tr></thead><tbody>{activity.map((row) => <tr key={row.start_date}><th scope="row">{row.label}</th><td>{row.count}</td></tr>)}</tbody></table></details>
      </AnalyticsPanel>
      <AnalyticsPanel title="Retailer and distributor mix" description={`Loaded page ${page} · ${visits.length} of ${matchedTotal} matching visits`} labelledBy="visits-field-mix" className="xl:col-span-2"><FieldMix metrics={model.fieldMix} total={model.representedTotal} /></AnalyticsPanel>
    </div>
    <details className="workspace-disclosure"><summary>Representative context · retained Visit authors</summary>{report.representatives ? <ul>{report.representatives.map((row) => <li key={row.user_id}><button type="button" className="min-h-11 text-left text-sm underline break-words" onClick={() => onRepresentative(row.user_id)}>{row.name || `Name unavailable · ${row.user_id}`} · {row.count.toLocaleString("en-IN")} retained visits</button><p className="break-all text-xs text-[var(--text-secondary)]">{row.user_id}</p></li>)}</ul> : <p role="status">Representative breakdown unavailable for more than 200 authors. Narrow the scope.</p>}</details>
    {report.date_mismatch_count > 0 && <p className="text-xs">{report.date_mismatch_count} records have a stored Visit date different from their IST check-in date. Charts use the canonical stored date.</p>}
  </section></AnalyticsBoundary>;
}
