"use client";

import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AnalyticsBoundary, AnalyticsEmptyState, AnalyticsPanel } from "@/components/analytics/AnalyticsPanel";
import { ChartContainer, ChartTooltipContent } from "@/components/analytics/Chart";
import { FieldMix } from "@/components/analytics/CompositionCharts";
import { buildVisitAnalytics, VISIT_OUTCOMES, type VisitAnalyticsSource } from "@/lib/analytics/viewModels";
import type { VisitRangeReport } from "@/lib/fieldVisits/range";
import { adminVisitOutcomeLabel } from "@/lib/fieldVisits/query";

export default function VisitSummaryCharts({ report, scope, matchedTotal, visits, page, onOutcome, onRepresentative }: {
  report: VisitRangeReport; scope: string; matchedTotal: number; visits: VisitAnalyticsSource[]; page: number;
  onOutcome: (key: string) => void; onRepresentative: (id: string) => void;
}) {
  const outcomes = report.outcomes.map((row) => ({ key: row.outcome, label: row.outcome === "unknown" ? "Unknown / legacy outcome" : adminVisitOutcomeLabel(row.outcome), value: row.count, color: VISIT_OUTCOMES.find((item) => item.key === row.outcome)?.color ?? "var(--viz-muted)" }));
  const model = buildVisitAnalytics(visits);
  return <AnalyticsBoundary><section aria-label="Full-range Visit activity" className="space-y-3">
    <header><h2 className="section-title">Retained visits across the applied range</h2><p className="text-sm"><strong>{report.retained_visit_count.toLocaleString("en-IN")}</strong> retained Visit records · {report.daily.length} IST business dates</p><p className="text-xs text-[var(--text-secondary)]">{scope}. Read at {new Date(report.generated_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST. Retained source exhausted; historical capture completeness is not certified. Live reads are not an atomic snapshot. Today, when included, is partial.</p></header>
    {matchedTotal !== report.retained_visit_count && <p role="status" className="alert-panel alert-panel--warning">Register and analysis were read at different times: {matchedTotal} matching records versus {report.retained_visit_count} retained observations. Refresh analysis to reconcile; neither count replaces the other.</p>}
    <div className="analytics-shell">
      <AnalyticsPanel title="Outcome composition" description="Full applied range · Each retained visit contributes to exactly one outcome. Select an outcome to filter the register and export." labelledBy="visits-outcome-donut">
        {report.retained_visit_count ? <div className="relative h-[280px]"><ResponsiveContainer width="100%" height="100%" initialDimension={{ width: 320, height: 280 }}><PieChart accessibilityLayer><Pie data={outcomes.filter((row) => row.value > 0)} dataKey="value" nameKey="label" innerRadius="62%" outerRadius="88%" stroke="var(--surface-primary)" isAnimationActive={false}>{outcomes.filter((row) => row.value > 0).map((row) => <Cell key={row.key} fill={row.color} />)}</Pie><Tooltip formatter={(value, _name, item) => [`${value} of ${report.retained_visit_count}`, item.payload.label]} contentStyle={{ backgroundColor: "var(--surface-elevated)", color: "var(--text-primary)", border: "1px solid var(--border-default)" }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><strong className="block text-3xl tabular-nums">{report.retained_visit_count}</strong><span className="text-xs">Full-range visits</span></div></div></div> : <AnalyticsEmptyState title="No retained visits match this range" description="Adjust the filters above to inspect another scope." />}
        <ul className="space-y-1 text-sm" aria-label="Visit outcome values">{outcomes.map((row) => <li key={row.key}>{row.key === "unknown" ? <div className="flex justify-between gap-3 py-2"><span>{row.label}</span><span>{row.value} of {report.retained_visit_count}</span></div> : <button type="button" className="flex min-h-11 w-full items-center justify-between gap-3 text-left underline underline-offset-4" aria-label={`Filter outcome: ${row.label}`} onClick={() => onOutcome(row.key)}><span><span className="mr-2 inline-block size-2 rounded-full" style={{ background: row.color }} />{row.label}</span><span className="shrink-0 tabular-nums">{row.value} of {report.retained_visit_count}</span></button>}</li>)}</ul>
      </AnalyticsPanel>
      <AnalyticsPanel title="Visit activity flow" description="Full applied range · Actual canonical Visit dates in Asia/Kolkata. Zero means no retained records, not zero employee activity. No growth or revenue is inferred." labelledBy="visits-activity-flow">
        <ChartContainer config={{ count: { label: "Retained visits", color: "var(--viz-primary)" } }} className="h-[280px] w-full" initialDimension={{ width: 520, height: 280 }}><AreaChart data={report.daily} accessibilityLayer margin={{ left: 0, right: 16, top: 16, bottom: 8 }}><CartesianGrid vertical={false} stroke="var(--viz-grid)" /><XAxis dataKey="date" tickFormatter={(value: string) => value.slice(5)} minTickGap={24} tickLine={false} axisLine={false} /><YAxis allowDecimals={false} domain={[0, "auto"]} width={40} tickLine={false} axisLine={false} /><Tooltip filterNull={false} content={<ChartTooltipContent />} /><Area dataKey="count" type="linear" connectNulls={false} stroke="var(--viz-primary)" fill="var(--viz-primary)" fillOpacity={0.18} strokeWidth={2} dot={{ r: 3 }} isAnimationActive={false} /></AreaChart></ChartContainer>
        <details className="workspace-disclosure"><summary>Exact daily chart data</summary><table className="w-full text-sm"><caption>Retained Visit records · {report.scope.date_from} to {report.scope.date_to} · IST</caption><thead><tr><th scope="col">Date</th><th scope="col">Retained visits</th></tr></thead><tbody>{report.daily.map((row) => <tr key={row.date}><th scope="row">{row.date}</th><td>{row.count}</td></tr>)}</tbody></table></details>
      </AnalyticsPanel>
      <AnalyticsPanel title="Retailer and distributor mix" description={`Loaded visits on this page · Page ${page} · ${visits.length} of ${matchedTotal} matching visits. Not a full-range segment breakdown.`} labelledBy="visits-field-mix" className="xl:col-span-2"><FieldMix metrics={model.fieldMix} total={model.representedTotal} /></AnalyticsPanel>
    </div>
    <details className="workspace-disclosure"><summary>Representative context · retained Visit authors</summary><p className="text-xs">Descriptive counts, not a performance ranking or current employee roster. Select an immutable identity to apply it to the register, analysis and export.</p>{report.representatives ? <ul>{report.representatives.map((row) => <li key={row.user_id}><button type="button" className="min-h-11 text-left text-sm underline break-words" onClick={() => onRepresentative(row.user_id)}>{row.name || `Name unavailable · ${row.user_id}`} · {row.count.toLocaleString("en-IN")} retained visits</button><p className="break-all text-xs text-[var(--text-secondary)]">{row.user_id}</p></li>)}</ul> : <p role="status">Representative breakdown unavailable: more than 200 retained authors. Narrow the range.</p>}</details>
    {report.date_mismatch_count > 0 && <p className="text-xs">{report.date_mismatch_count} retained records have a stored Visit date different from their IST check-in date. This chart uses the stored canonical Visit date.</p>}
  </section></AnalyticsBoundary>;
}
