"use client";
import { useCallback, useEffect, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { fetchReceivables, executeReceivableCommand, recoverReceivableCommands } from "@/lib/receivables/client";
import type { ReceivableSummary } from "@/lib/receivables/types";
import { formatInr } from "@/lib/receivables/domain";
import { MAX_IMPORT_BYTES, parseReceivablesTable, type ImportRow } from "@/lib/receivables/import";
import { supabase } from "@/lib/supabaseClient";
import { PageHeader } from "@/components/ui/PageHeader"; import { Button } from "@/components/ui/Button"; import { Input } from "@/components/ui/Input"; import { Chip } from "@/components/ui/Chip";
interface AdminSummary { total_outstanding:string; followups_due_today:number; overdue_outstanding:string; collected_this_month:string; awaiting_verification:number; aging:Record<string,string> }
interface PendingPayment { payment_id:string; receivable_id:string; amount:string; payment_date:string; payment_reference:string|null; reporter_name:string; receivable:{distributor_name:string;bill_reference:string;outstanding_amount:string;version:number} }

export default function AdminPaymentsPage() {
 const { isAdmin, allUsers }=useAuth(); const [rows,setRows]=useState<ReceivableSummary[]>([]); const [page,setPage]=useState(1); const [total,setTotal]=useState(0); const [search,setSearch]=useState(""); const [message,setMessage]=useState(""); const [summary,setSummary]=useState<AdminSummary|null>(null); const [pending,setPending]=useState<PendingPayment[]>([]); const [importRows,setImportRows]=useState<ImportRow[]>([]); const [importInvalid,setImportInvalid]=useState(0); const [importName,setImportName]=useState(""); const [importOperation,setImportOperation]=useState("");
 const load=useCallback(async()=>{try{const [r,auth]=await Promise.all([fetchReceivables(`?page=${page}&pageSize=20&search=${encodeURIComponent(search)}`),supabase.auth.getSession()]);setRows(r.rows);setTotal(r.total);const token=auth.data.session?.access_token;if(token){const response=await fetch("/api/receivables/admin",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(response.ok){const result=await response.json();setSummary(result.metrics);setPending(result.pending)}}}catch(e){setMessage(e instanceof Error?e.message:"Unavailable")}},[page,search]); useEffect(()=>{if(isAdmin)void recoverReceivableCommands().then(result=>{if(result.confirmed)setMessage(`${result.confirmed} uncertain action was confirmed.`);void load()}).catch(()=>void load())},[isAdmin,load]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,payload=Object.fromEntries(new FormData(form).entries());Object.assign(payload,{receivable_id:crypto.randomUUID()});try{await executeReceivableCommand({operation_id:crypto.randomUUID(),operation_type:"create",payload});form.reset();setMessage("Receivable created and confirmed.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Not confirmed")}}
 async function chooseFile(file:File){try{if(file.size>MAX_IMPORT_BYTES)throw new Error("Maximum file size is 10 MB.");const XLSX=await import("xlsx");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];const parsed=parseReceivablesTable(XLSX.utils.sheet_to_json(sheet,{header:1,raw:true}) as (string|number|boolean|Date|null|undefined)[][]);setImportRows(parsed.rows);setImportInvalid(parsed.invalid.length);setImportName(file.name);setImportOperation(crypto.randomUUID());setMessage(`Preview ready: ${parsed.rows.length} valid, ${parsed.invalid.length} invalid. Nothing has been written.`)}catch(e){setMessage(e instanceof Error?e.message:"File could not be parsed.")}}
 async function confirmImport(){const {data}=await supabase.auth.getSession();if(!data.session?.access_token)return;const response=await fetch("/api/receivables/import",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({mode:"confirm",operation_id:importOperation,filename:importName,rows:importRows})});const result=await response.json();if(!response.ok){setMessage(result.message??"Import was not confirmed.");return}setMessage(`Batch confirmed: ${result.created_count} created, ${result.duplicate_count} exact duplicates skipped.`);setImportRows([]);await load()}
 async function verify(payment:PendingPayment,confirm:boolean){const reason=confirm?null:window.prompt("Rejection reason");if(!confirm&&!reason)return;const next=confirm&&payment.amount!==payment.receivable.outstanding_amount?window.prompt("Next follow-up date (YYYY-MM-DD)"):null;try{await executeReceivableCommand({operation_id:crypto.randomUUID(),operation_type:confirm?"confirm_payment":"reject_payment",payload:{receivable_id:payment.receivable_id,payment_id:payment.payment_id,expected_version:payment.receivable.version,...(reason?{reason}:{}),...(next?{next_follow_up_date:next}:{})}});setMessage(confirm?"Payment confirmed against the authoritative balance.":"Payment report rejected; collection alerting resumed.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Verification was not confirmed.")}}
 if(!isAdmin)return <div className="app-page"><PageHeader title="Payment Collections" description="System Administrator access required."/></div>;
 const fields=[["distributor_name","Distributor Name"],["distributor_code","Distributor Code / Username"],["bill_reference","Bill / Invoice Reference"],["contact_person","Contact Person"],["contact_phone","Contact Phone"],["bill_amount","Bill Amount"],["bill_due_date","Bill Due Date"],["next_follow_up_date","Payment Follow-up Date"]];
 return <div className="app-page"><PageHeader eyebrow="Financial operations" icon={<ShieldCheck size={16}/>} title="Payment Collections" description="Authoritative receivables, payment verification, aging, and audit-ready actions."/>{message&&<div className="alert-panel alert-panel--info" role="status">{message}</div>}
  {summary&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total Outstanding",formatInr(summary.total_outstanding)],["Follow-ups Due Today",String(summary.followups_due_today)],["Overdue Outstanding",formatInr(summary.overdue_outstanding)],["Collected This Month",formatInr(summary.collected_this_month)],["Awaiting Verification",String(summary.awaiting_verification)]].map(([label,value])=><div className="surface-panel p-4" key={label}><p className="text-[10px] font-semibold uppercase text-[var(--text-muted)]">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums">{value}</p></div>)}</div><section className="surface-panel p-4"><h2 className="section-title">Aging</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">{Object.entries(summary.aging).map(([bucket,amount])=><div key={bucket}><p className="text-xs text-[var(--text-muted)]">{bucket}</p><p className="font-semibold tabular-nums">{formatInr(amount)}</p></div>)}</div></section></>}
  {pending.length>0&&<section className="rounded-[var(--radius-xl)] border-2 border-[var(--status-warning)]/40 bg-[var(--status-warning-soft)] p-5"><h2 className="section-title">Payment reports awaiting verification</h2><div className="mt-3 grid gap-3">{pending.map(payment=><article className="rounded-[var(--radius-lg)] bg-[var(--surface-primary)] p-4" key={payment.payment_id}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{payment.receivable.distributor_name} · {payment.receivable.bill_reference}</p><p className="mt-1 text-sm">Reported {formatInr(payment.amount)} · outstanding {formatInr(payment.receivable.outstanding_amount)}</p><p className="text-xs text-[var(--text-muted)]">{payment.reporter_name} · {payment.payment_date} · {payment.payment_reference??"No reference"}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void verify(payment,false)}>Reject</Button><Button onClick={()=>void verify(payment,true)}>Confirm</Button></div></div></article>)}</div></section>}
  <section className="surface-panel p-5"><h2 className="section-title">Manual entry</h2><form className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4" onSubmit={create}>{fields.map(([name,label])=><Input key={name} name={name} label={label} required={!name.includes("code")&&!name.includes("phone")} type={name.includes("date")?"date":"text"}/>)}<label className="text-xs font-semibold">Assigned Employee *<select name="assigned_to" required className="field-control mt-1"><option value="">Select active employee</option>{allUsers.filter(u=>Boolean(u.is_active)).map(u=><option value={u.user_id} key={u.user_id}>{u.name} · {u.email}</option>)}</select></label><Input name="note" label="Notes"/><div className="flex items-end"><Button type="submit">Create receivable</Button></div></form></section>
  <section className="surface-panel p-5"><h2 className="section-title">Excel import</h2><p className="mt-1 text-xs text-[var(--text-muted)]">XLSX, XLS, or CSV · 10 MB · 5,000 rows. Preview never writes.</p><input className="mt-3 block text-sm" type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const file=e.target.files?.[0];if(file)void chooseFile(file)}}/>{importRows.length>0&&<div className="mt-3 flex flex-wrap items-center gap-3"><Chip variant="success">{importRows.length} valid</Chip><Chip variant={importInvalid?"danger":"neutral"}>{importInvalid} invalid</Chip><Button disabled={importInvalid>0} onClick={()=>void confirmImport()}>Confirm atomic import</Button></div>}</section>
  <section className="surface-panel overflow-hidden"><div className="surface-toolbar m-4"><Input aria-label="Search collections" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search distributor or bill"/><Chip variant="neutral">{total} records</Chip></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-y border-[var(--border-subtle)] bg-[var(--surface-secondary)]">{["Distributor","Contact","Bill Reference","Bill Amount","Received","Outstanding","Bill Due","Next Follow-up","Owner","Status"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-b border-[var(--border-subtle)]" key={r.receivable_id}><td className="p-3 font-semibold">{r.distributor_name}</td><td className="p-3">{r.contact_person}</td><td className="p-3">{r.bill_reference}</td><td className="p-3 tabular-nums">{formatInr(r.bill_amount)}</td><td className="p-3 tabular-nums">{formatInr(r.confirmed_paid_amount)}</td><td className="p-3 font-semibold tabular-nums">{formatInr(r.outstanding_amount)}</td><td className="p-3">{r.bill_due_date}</td><td className="p-3">{r.next_follow_up_date??"—"}</td><td className="p-3">{r.owner_name}</td><td className="p-3"><Chip size="sm" variant={r.payment_state==="Paid"?"success":r.pending_payment_count?"warning":"neutral"}>{r.pending_payment_count?"Awaiting verification":r.payment_state}</Chip></td></tr>)}</tbody></table></div><div className="flex justify-between p-4"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="text-xs">Page {page}</span><Button variant="outline" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</Button></div></section>
 </div>
}
